### ISSUE TITLE
[Feature Request] Expose Secrets and Configmaps as Environment Variables

### ISSUE THREAD

**Issue by mattroark** [fission/fission#1122]
Presently, secrets and configmaps are exposed via file mounts [1].

K8s supports exposing these as environment variables as well though [2][3]. It would be convenient to be able to directly utilize the environment variables vs reading from a file, the latter of which requires many more lines of code. 

[1] https://docs.fission.io/usage/access-secret-cfgmap-in-function/
[2] https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
[3] https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-container-environment-variables-using-configmap-data

**Comment by soamvasani** [comment]
Hmm, this is a fairly popular request, but it's not easy to implement.  For the newdeploy executor it would be easy enough; for poolmgr, it's not easy at all, because the container is running before the function is invoked, and the environment of the container is set up when the container was created; in other words at the time the container starts, we don't know which function will run in it and which env vars to set. 

We could solve this by having the environments themselves implement this in `specialize`, since a process can easily change its own environment; but it would require an interface change in the `FunctionLoadRequest` (and an environment version number bump) and a small implementation change in every language environment.

**Comment by viveksinghggits** [comment]
Hey @mattroark ,
Can you please look into https://github.com/fission/fission/pull/1369 and https://blog.fission.io/posts/fission_pod_specs/, I think that can be achieved using `PodSpec` for environment and builder.

**Comment by life1347** [comment]
PodSpec supports this feature now. Please visit [here](https://docs.fission.io/docs/spec/podspec/envvar/#expose-secret-configmap-as-environment-variable). Feel free to reopen it.
