### ISSUE TITLE
Fission spec apply does not refresh the configmap and secret

### ISSUE THREAD

**Issue by hd40910** [fission/fission#1161]
If we create a configmap or secret and pass it to the fission function spec and apply it.
After this we change the configmap or secret, the new changes should be available in  the function.
It does not become available even after we reapply the spec.

The only way to get the new cm or secret is to first delete the resource and then recreate the function.

Spec file :

![image](https://user-images.githubusercontent.com/17830882/55971832-e00cc700-5c9f-11e9-900e-c0c72cd33b0f.png)

**Comment by viveksinghggits** [comment]
The changed values do get updated but they take some time, can you try testing the function after some time, when you change the config map. I think you dont even need to apply the spec after changing the config map.

**Comment by life1347** [comment]
Hi @hd40910 
The way for a function to access secrets/configmaps is different from the kubernetes built-in mechanism.

Unlike kubernetes mounts a volume to the pod, the fetcher inside function pod fetches secrets/configmaps during the [specialization](https://github.com/fission/fission/blob/8015ab9a1e255a6de5b0fc54e5aee35ec094b1d5/environments/fetcher/fetcher.go#L598), which means the content of secrets/configmaps won't change even the source changed until  executor reap the pod and specialize a new one.

A workaround for this issue is to update with the same code/package for function

**Comment by hd40910** [comment]
@life1347  Can you please help explain "A workaround for this issue is to update with the same code/package for function" ?

We deploying all the functions in one go, the config maps gets updated once in a while.

**Comment by life1347** [comment]
I mean you can redeploy the function (`fission spec apply`). Once the executor detects there is a new version of the function, it will then select a new pod for specialization to serve the request. And the latest secrets/configmaps will be download during the specialization.
