### ISSUE TITLE
Datatype for UID in fission-deployment-config.yaml

### ISSUE THREAD

**Issue by msshroff** [fission/fission#1232]
We are using specs for doing all the deployments on fission. 
Building the specs on the CI server and then pushing the created specs on PROD for deployment. 
We recreate the specs dynamically for every build, which obviously creates new UID in fission-deployment-config.yaml

With this approach when we deploy the incremental changes to PROD, it fails with duplicate resource error. 

To overcome this, we are replacing the UID in fission-deployment-config.yaml with function name post specs are created. 
In below example replacing **uid: b16b8e4d-cb83-4197-8892-9cdaa7eb5a7f** with **uid: test-function-name**

Currently this approach is working for us.
So just wanted to understand, if there are any validations for UID which may fail in future? 
Any limitations? 
Will this approach has any risks? 

<pre>
$ cat fission-deployment-config.yaml.original
apiVersion: fission.io/v1
kind: DeploymentConfig
name: customer-status-csm
uid: b16b8e4d-cb83-4197-8892-9cdaa7eb5a7f

$ cat fission-deployment-config.yaml
apiVersion: fission.io/v1
kind: DeploymentConfig
name: customer-status-csm
uid: test-function-name

</pre>

**Comment by life1347** [comment]
I cannot guarantee the future things, but I think maybe we can provide a flag for the user to specify UID when doing `fission spec init`? @soamvasani ?

**Comment by life1347** [comment]
@msshroff 

BTW, may I ask how your workflow works?

Cause the original idea of `fission spec` is that `spec` will be stored in the version control system and users only need to push files that changed instead of recreating the whole spec. But from your use case, sounds like things are getting down in CI/CD pipeline and that's why you face this problem.

It would be great if you can share more information about how your pipeline works and other points that may help to increase the experience so that we can head in the right direction.

So far, I can only think of an issue that might be the problem: `fission spec` is not smart enough to update/remove spec files if there are any changes. For example,
```
$ fission spec init
$ fission env create --name java1 --image fission/jvm-env --builder fission/jvm-builder --spec
$ fission env create --name java1 --image fission/jvm-env --version 3 --poolsize 2 --spec
$ cat specs/env-java1.yaml
# shows duplicate envs
```

**Comment by msshroff** [comment]
@life1347 

Below is out high level workflow 

1. Fission function created by the developers, they will also create yaml for CM and Secret in corresponding directory structure
2. The CI process dynamically generate the specs for each function (and changes needed for corresponding CM, Secrets, ht, mqt etc) 
3. CI Process packs created fission specs in the build process (point 2) 
4. CD process takes the build and runs "fission spec apply" for each deployment 

Here only artifacts created in Point 1 are in version control system(GIT).
We are not putting specs in GIT as it need some info about ht, mqt, global CMs which developers do not know about.

**Comment by life1347** [comment]
@msshroff This feature has been added to 1.5 which will be shipped this weekend. And thanks for the high-level workflow that's really helpful.
