### ISSUE TITLE
support for providing request body while calling fission function through time trigger

### ISSUE THREAD

**Issue by viveksinghggits** [fission/fission#1288]
We should have a way to provide a request body, the fission function will be called with, when the function is being called via `time trigger`. For example when a fission function gets called via `mq trigger` the functions get the data that was put into the kafka topic as request body, similarly we can have some data (may be maintained in configmap or can be provided in the CLI itself), that will passes to the function as request  body.

**Comment by vishal-biyani** [comment]
@viveksinghggits I am assuming you would want to send the same body every time the function is called with the time trigger?

**Comment by viveksinghggits** [comment]
@vishal-biyani yes, I want able to think how are we going to provide dynamic data every time thats why thought it should be called with the constant data every time that function is called.

**Comment by life1347** [comment]
I'm wondering is there any reason for not reading the request body from configmaps and/or secrets since we are already able to do that? 
1. The main goal of time trigger is to trigger a job periodically like cronjob in Linux, I think we should keep it simple. 
2. The [rollout feature](https://github.com/fission/fission/pull/1224) added in 1.4 is quite useful for this case.
3. This field can only be used in time trigger
4. Extra complexity for the management of the request body.

I think it would be great to add this feature if we have more strong use cases that worth to add extra flags to the CLI.

**Comment by viveksinghggits** [comment]
Hi @life1347 
I agree, with you that `time trigger` should be responsible for calling the function periodically like cornjob and adding another will make in unnecessarily complex. 
I think you can close the issue if you want to.
