### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by tx19980520** [fission/fission#1421]
My issue is about using fission at nanopc-t4, which is an IoT with arm64. But I see that maybe most of fission images is amd64 on dockerhub.Or maybe you have the way to install on an IoT with arm64.
environment: k3s 0.9.1

**Comment by life1347** [comment]
If you don't mind contributing to Fission, you can continue this closed PR https://github.com/fission/fission/pull/1313 for arm platform.

**Comment by tx19980520** [comment]
I think maybe use docker 19.03 new feature can solve the problem fundamentally.
I used `docker buildx build` to build arm64 container easily at my amd64 machine. I have seen that the issue you have mention mainly change Dockerfile about `go build` target to specific machine.
If you think we can use `docker buildx` to solve the problem without injury，I would like to be a contributor.

**Comment by life1347** [comment]
Yes, I think `docker buildx build` should be able to solve the platform supportability problem. The PR1313 already addressed the supportability problem for Fission core components. The rest of the part of work is to make language environment support arm64. 

You can try to modify the Dockerfile of the language environment that well-support arm64, like go. Here is a useful reference: https://docs.docker.com/buildx/working-with-buildx/

One thing worth to notice is that `docker buildx` is still an experimental feature as mentioned in the link above. Since some users already use Fission on production, we may not be able to merge the new PR in a short time unless we can confirm there is no potential issue that will break the system.

**Comment by cerebrate** [comment]
Just FYI, I've hacked together a working version of 1.11.2 core and two of the environments (nodejs and python) as amd64/arm multi-arch images using docker buildx. (My images here - https://hub.docker.com/u/cerebrate - if anyone's curious.) I've found some minor issues with the binary environment that evidently buildx can't fix alone, and not knowing Go, I haven't been able to pursue that much further.

Happy to PR what I've got if it would be useful.

**Comment by vishal-biyani** [comment]
Hi @cerebrate This is great 🎉 We would love to have this merged in Fission. It would be great if you can send PR for Fission changes to this repo and environment changes to https://github.com/fission/environments repo, please. We are in the middle of moving environments so right now you see them both the places. Please let me know if we can help you in any possible way!

**Comment by RealHarshThakur** [comment]
Related: https://github.com/fission/fission/pull/1929

**Comment by sanketsudake** [comment]
Fission now has support for ARM with Fission CLI as well as images since 1.13.0 release. Closing the issue.
