### ISSUE TITLE
Why does poolmanager support only one pod per function

### ISSUE THREAD

**Issue by andyyin** [fission/fission#1438]

**Comment by life1347** [comment]
It's an intentional design. Poolmanger is for the short-living functions and the functions do not require to handle massive traffic. 

The executor will recycle the pod if no traffic to the function after some periods. By recycling idle pod we can release resources for other services in the cluster to increase resource utilization. 

If you want more than one function pods to serve the function, please use newdeploy instead. Docs: https://docs.fission.io/docs/concepts/components/core/executor/#new-deployment

**Comment by andyyin** [comment]
> It's an intentional design. Poolmanger is for the short-living functions and the functions do not require to handle massive traffic.
> 
> The executor will recycle the pod if no traffic to the function after some periods. By recycling idle pod we can release resources for other services in the cluster to increase resource utilization.
> 
> If you want more than one function pods to serve the function, please use newdeploy instead. Docs: https://docs.fission.io/docs/concepts/components/core/executor/#new-deployment

I see, Thank you. It would be better if poolmanager and newdeploy can be combined, both low latency and less waste of resources. Is there the plan for future fission.

**Comment by life1347** [comment]
We are investigating different approaches, but haven't had a clear plan right now. For now, I would suggest using newdeploy since you will only experience the cold start time in the beginning.

Close, feel free to reopen it.
