### ISSUE TITLE
Not able to access url in java funtion 

### ISSUE THREAD

**Issue by AshishJainRadicle** [fission/fission#1552]
@anubhav6663 
We are creating a route for our function as following:

`fission-cli-windows.exe route create --function service --url dev/unimarket/service --createingress --method POST`

We are able to access the java function by url "https://fission.lingkcore.com/dev/unimarket/service".
but not able to get the full url in the code. We have used  "req.getUrl()" where "req" is the object of RequestEntity to get the url but it is returning http://192.168.98.133:8888/ along with query string.

Is there any other method to get the actual request url?

**Comment by dalemccrory** [comment]
The core architectural issue related to not being able to access to the URL is that developers are unable to use REST libraries out-of-the-box routing capabilities. 

If the function was able to see the source URL, then you could map multiple HTTP endpoints to a single function and have the function handle the different capabilities.

**Comment by life1347** [comment]
Have you tried with `X-Fission-Full-Url` in request header? https://github.com/fission/fission/pull/1266

**Comment by dalemccrory** [comment]
@AshishJainRadicle So you could potentially use an approach like:
https://stackoverflow.com/a/28978111
with 
`X-Fission-Full-Url` 

@life1347 just to educate me... why can't the original headers be passed through the ingress? Since the X-Header approach still requires additional knowledge to implement both of Fission and Java.

**Comment by life1347** [comment]
Fission runtime loads the user's function and exposes it at `/` instead of the URL that client hits (`/dev/unimarket/service`), if the router uses the original URL it won't be able to hit the endpoint. 

https://github.com/fission/fission/blob/4fb1a8fbe8e52c0b0bf4ef3f19b02a79d8639a25/pkg/router/functionHandler.go#L226-L231

**Comment by vishal-biyani** [comment]
As stated by @life1347 I think the only way to pass some specific headers is to use the X- format because of the way Function endpoints are designed today. I will close this issue for now but we can revisit if needed in the future.
