### ISSUE TITLE
Controlling concurrency of function executions within a Pod 

### ISSUE THREAD

**Issue by slayerjain** [fission/fission#1628]
I have a java function that requires at least 2 CPU cores to complete execution in the required time. I've tried modeling it as a pod (and have that pod CPU request/limit 2), exposed as an HTTP server, and setup HPA but couldn't find a way to ensure that one pod is serving only one request at a time. Other applications are accessing the pods internally using k8s `service` object. I have fission infrastructure already in my cluster and want to create a fission function that can be triggered via HTTP and ensure each invocation gets 2 CPU cores. 

In Knative I've found I can control concurrency per pod (which can solve my problem). As @vishal-biyani mentioned on slack, there is a parameter that allows concurrency controls in Fission too (`AllowedFunctionsPerContainer` attribute in environment spec). It would be great to have more resources/docs on this :)

**Comment by slayerjain** [comment]
Just tried setting it to `single` but it still runs multiple requests in the same pod

**Comment by slayerjain** [comment]
`apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: dev
  namespace: default
spec:
  builder:
    command: build
    image: fission/jvm-builder
  imagepullsecret: ""
  keeparchive: true
  poolsize: 1
  allowedFunctionsPerContainer: single
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 1Gi
  runtime:
    image: fission/jvm-env
  version: 3`

**Comment by vishal-biyani** [comment]
Closed by #1698 - will be available in release 1.11.0

**Comment by airhorns** [comment]
I think that #1698 is actually about something different. That PR lets people control how many pods are dedicated to a given function's execution from an environment's poolmgr. The way I read this issue I think @slayerjain wants to be able to control the number of requests sent to one pod simultaneously. For them, they want to set it to 1 to guarantee all the pod's resources to processing that one request, but I think for lots of other functions, you want the opposite and to let many requests go to the same backend instance. AFAICT right now fission hardcodes the requests-per-pod limit to 1, which means if you want more throughput you have to spawn a lot of pods which uses a lot more memory, reduces cache locality, increases backend connection counts, etc, or you have to use NewDeploy, which means you lose the cold start time that Fission is famous for and the elasticity among functions using the same environment.

I would love to see a user-controllable requests-per-pod concurrency limit, and I think it might make sense to change the default away from 1 to keep the system as efficient as possible by default! Especially since `node.js` seems to be the default runtime that a lot of the Fission examples use and a lot of developers seem to be choosing for functions these days. Node is great at handling many many requests at once, and developers have to take care to use it's asynchronous facilities to keep that alive. If their production node processes only serve one request simultaneously, all that is kind of wasted effort, you know?

**Comment by airhorns** [comment]
Is this the issue where we should follow along if we're interested in multiple-requests-per-pod support or is there another one that I can't find? Thanks!!

**Comment by vishal-biyani** [comment]
@airhorns I just created an issue to track it here: https://github.com/fission/fission/issues/1888 Please feel free to add more scenarios there.
