### ISSUE TITLE
Ingress integration

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#164]
We should add an "ingress" field to our HTTP trigger objects, and create Kubernetes ingress objects for those routes.  That way, the fission router doesn't need to be exposed on an ingress as a whole, and the user can control more finely what is exposed to the outside world.

**Comment by tobilarscheid** [comment]
Sounds very reasonable!

**Comment by 7agustibm** [comment]
I have ingress with traefik. How can I help?

**Comment by vishal-biyani** [comment]
Ingress integration design:

## Goal
A user should be able to add an ingress path while creating the route for the function and the function should be available at that ingress path (provided the ingress controller is deployed already and DNS settings etc. point appropriately to the Ingress Controller etc.)

## Design

The HTTPTrigger object represents the object and has following fields:

```
HTTPTriggerSpec struct {
		Host              string            `json:"host"`
		RelativeURL       string            `json:"relativeurl"`
		Method            string            `json:"method"`
		FunctionReference FunctionReference `json:"functionref"`
	}
```
Assuming that the ```RelativeURL``` will be same on router as well as the ingress - we can simply add a boolean flag which allows user to create a ingress resource for the function.

```
HTTPTriggerSpec struct {
		Host              string            `json:"host"`
		RelativeURL       string            `json:"relativeurl"`
		Method            string            `json:"method"`
		CreateIngress     bool              `json:"createingress"`
		FunctionReference FunctionReference `json:"functionref"`
	}
```
As soon as a user creates the route and if ingress flag is true, the ingress resource will be created. Assuming `/greet` is the route, we can create an equivalent ingress resource:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: greet
  namespace: ingress-nginx
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: fission-router
          servicePort: 80
        path: /greet
```
### Flow

Overall flow of the function call when using an ingress controller will look like below:

![screen shot 2018-05-16 at 5 01 21 pm](https://user-images.githubusercontent.com/1167948/40114504-cfca7d16-592a-11e8-9bb8-b8518ca29e57.png)

User hits the FQDN of function, which is forwarded to load balancer of the ingress controller.  The ingress controller has the mapping for the `/greet` which maps to fission router's path `/greet`. After fission router recieves the request - it then forwards to appropriate function pod/svc.

### Open Questions & Limitations

1.  Are there reasons to have the function's internal URL different than the ingress path?

2. If a user creates an ingress for a function, should Fission not expose the function on fission router's load balancer at all by default? (Which also means the ingress controller should route to `/fission-function/function_name` instead of path relative to the Fission router service.

3. The current design also does not allow you to specify the host - which can be useful in certain scenarios.

```
spec:
  rules:
  - host: demo.fission.space
```
4. Lastly a lot of behaviour of ingress can be affected by [annotations at ingress resource level](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md). Many of these annotations are used by users to affect small change in behaviour for that ingress record. 

Some of these behaviours can be set at ingress controller level itself using configmap.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
```

### Design V2
To accomodate specifically (3) and (4) from above, we need more fields for ingress related specs in the route. So revised httptriggerspec looks like below. This still opens up more questions discussed after this code snippet

```
HTTPTriggerSpec struct {
		Host              string            `json:"host"`
		RelativeURL       string            `json:"relativeurl"`
		Method            string            `json:"method"`
		IngressSpec       IngressSpec       `json:"ingressspec"`
		FunctionReference FunctionReference `json:"functionref"`
	}
```
And ingressspec:
```
	IngressSpec struct {
		CreateIngress      bool
		IngressPath        string
		IngressHost        string
		IngressAnnotations map[string]string
	}
```
This still leaves some open questions:

1. Fission router is further passing the request to the pod. Some of annotations expect that the responding pod will do certain things, with router in between the controller and pod, some things may not work as expected.

Overall - I think it makes sense to support the barebones ingress in V1 and in future enhance it if needed to add support for v2 features

**Footnotes**

The sequence diagram was created using [MermaidJS](https://mermaidjs.github.io/mermaid-live-editor/). The code below can be used to re-create it:
```
sequenceDiagram
    participant dns as Domain Name
    participant lb as Load Balancer
    participant ig as Ingress Controllerr
    Note right of ig: ingress greet present
    participant fr as Fission Router
    participant fp as Function Pod Svc
dns->>lb: host/greet
lb->>ig: /greet
ig->>fr: /greet
fr->>fp: greet function call
fp->>dns: Return Function Response
```

**Comment by vishal-biyani** [comment]
Resolved by #688

**Comment by activeshadow** [comment]
Did #688 add support for ingress annotations? If so, I'm not seeing how to add them. As a specific example, I'm wanting to enable `cert-manager` for ingress resources created by Fission for externally-exposed functions.

**Comment by life1347** [comment]
track by https://github.com/fission/fission/issues/989
