### ISSUE TITLE
OpenTelemetry tracing support & context propagation

### ISSUE THREAD

**Issue by airhorns** [fission/fission#1861]
**Is your feature request related to a problem? Please describe.**

Currently, Fission supports outputting traces to an OpenTracing Jaeger-formatted trace collection endpoint. This is great -- it provides lots of insight into what Fission is doing and helps operators understand and maintain.

**Describe the solution you'd like**

OpenTracing has been merged with OpenCensus into a new open source org called OpenTelemetry, and they've re-specified their trace propagation spec and trace format. Specifically there's three things that Fission could to do to better support tracing:

 - move to the OpenTelemetry library system as it is maintained, getting new features, and supports the new seemingly preferred trace format which is Jaeger's GRPC trace format (on port 14250 by default, referred to as `model.proto` see [their docs](https://www.jaegertracing.io/docs/1.21/getting-started/#all-in-one)). Currently, it seems like Fission only supports the older, less efficient Jaeger thrift format.
 - using OpenTelemetry, allow trace parents to be sent to functions, so fission can be within a trace instead of always the root. Right now, Fission's tracing support doesn't support OpenTelemetry's trace context propagation headers, which would allow Fission to report the spans it generates as children of a caller. In practice, this means if you are invoking fission functions from other services, you lose your tracing context instead of seeing it as one big nice trace. It'd be awesome to see a trace that originated from some frontend HTTP call go through various services including fission all the way into the function being executed, and OpenTelemetry context propagation should give Fission that for free.
 - allow some spans to be suppressed, like those for the healthcheck endpoints of the components that have them. We're generating a bunch of extra spans that I feel like I don't need to store. I think there are ways to filter these out downstream, but it would be nice to just never produce them in the first place. Configuring the whole of the OpenTelemetry exporter stack via environment variables doesn't sound super fun, but at least some way of lowering the data volume would be grand. 

**Describe alternatives you've considered**

OpenTracing works fine right now, and I haven't tested if passing OpenTracing context propagation headers to fission works. 

**Additional context**

I am not sure there is an official word from the OpenTracing folks, but it seems like all the development effort is behind OpenTelemetry. A bunch of observability vendors have thrown their weight behind OpenTelemetry, and the trace propagation spec that otel implements is being developed at the W3C and I think is likely to last a lot longer than OpenTracing's.

**Comment by vishal-biyani** [comment]
Hi @airhorns - thanks for detailed notes and observations from the current implementation. I will take a look at what is happening in the open telemetry world and then accordingly design and prioritize this.

**Comment by vishal-biyani** [comment]
Discussion update from @airhorns: 

OpenTelemetry integration. Right now Fission has support for OpenTracing, which is good but not great. It's a bit less configurable than OpenTelemetry and the project has been deprecated since it merged with OpenCensus. We'd love to be able to send requests to fission with the tracing headers for an existing trace and have fission accept those, note how long specialization takes if necessary, and pass the tracing context through in the request to the actual function pod, giving end to end tracing visibility from outer services calling into fission. Right now, I don't think fission's opentracing system correctly propagates headers sent according to the otel spec. The otel spec hit 1.0 recently so hopefully this would be much more stable for a while. Also important would be the ability to disable tracing events for the health check endpoints, right now fission's healthchecks account for like 50% of our production tracing volume which seems silly. We can filter them out downstream but i imagine most people would prefer that to be the case by default

**Comment by sanketsudake** [comment]
Related PRs

https://github.com/fission/fission/pull/2157
https://github.com/fission/fission/pull/2172
https://github.com/fission/fission/pull/2175
https://github.com/fission/fission/pull/2180
https://github.com/fission/fission/pull/2194
https://github.com/fission/fission/pull/2201
