### ISSUE TITLE
Support for queuing mechanism in case of poolmngr if concurrency limit is reached.

### ISSUE THREAD

**Issue by abbaspw21** [fission/fission#1877]
**Is your feature request related to a problem? Please describe.**
In fission 1.11.0 concurrency support was added for Poolmngr fission functions but in this case if concurrency is reached then fission function fails with error 502 for sync call. 

**Describe the solution you'd like**
We are looking for an optional queuing mechanism (environment or function level) so that in case if concurrency limit is reached for sync call then the incoming sync calls get queued as it used to without concurrency support. 

For some constraints its not possible to use message queue for the above calls.

**Additional context**
https://github.com/fission/fission/issues/1852

**Comment by vishal-biyani** [comment]
Hey @abbaspw21  The concurrency is intended to put a rate limit on functions and if your requests are getting dropped - I recommend increasing the concurrency. Is there a reason you can not increase concurrency? The whole idea is to keep a concurrency higher than the calls you are expecting concurrently; it won't create those many pods unless requests come in.

One other way this can be handled by the client is by checking the HTTP Response code - ideally, it should be HTTP 429 but it is not due to https://github.com/fission/fission/issues/1875. If the client gets 429 - it should be tried with a retry backoff mechanism.

Keeping an HTTP call waiting till more workers are available is not a scalable solution - in which it is better to use an MQ to call a function.

**Comment by vishal-biyani** [comment]
Hey @abbaspw21 I will close this issue for now but please reopen if needed.
