### ISSUE TITLE
Fission API needs authentication

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#22]
Fission API needs some sort of authentication, either with client certs or some sort of user/password file.

**Comment by seriousme** [comment]
[OpenWhisk](http://openwhisk.org/) only uses basic authentication for now and has the concept of public (open to anyone) and private functions. For more details see: https://github.com/openwhisk/openwhisk/blob/master/docs/reference.md

To go beyond that one could use the same method as Kubernetes (and maybe even the same code ;-))
Kubernetes uses a plugable authentication mechanism on its API server and the same for authorization.
(see https://kubernetes.io/docs/admin/authentication/)
The API server has no clue what methods exist, the auth/authz plugable modules do all the work.

**Comment by soamvasani** [comment]
Just to clarify, this bug is about authentication for the Fission API itself, not the user's fission functions.

Pluggable auth is nice but feels like a bit overkill for now for our small API.  I'd be happy to have HTTP basic auth until someone shows up with a use case where that doesn't work for them.

**Comment by seriousme** [comment]
Thats why I listed both options ;-)

I agree that for now basic auth will be enough to authenticate fission admins as its good enough for IBM. 

However If you want to host this for multiple tennants then I presume basic auth will rather inconvenient, so for the long term you might want to expand on that.

**Comment by emaildanwilson** [comment]
Perhaps basic auth coupled with examples for how to deploy fission in another namespace would be sufficient for a long while. That way each k8s namespace can manage their own fission environment and security. Would that make sense?

**Comment by jokeyrhyme** [comment]
I've been thinking about both authentication and authorisation (a.k.a. "authorization" for you Z-ers) and I can see a few usage scenarios that would be desirable:

1. all k8s users that can deploy to the namespace also need to deploy to fission in that namespace

2. there are users that need to deploy to fission but otherwise have no k8s powers

3. there are k8s users that should not have any fission powers

4. there are users that should be able to manage specific functions and routes in fission, but not have any powers at all over other functions and routes

Case 3 seems a little pointless, so we can probably ignore that. Case 4 is really just a more granular / more specific version of Case 2.

I'd suggest that supporting Case 1 is probably a good interim solution, but ultimately Case 2 / 4 is probably a better long-term plan.

**Comment by seriousme** [comment]
Now the question is: do you want to build this all yourself or do you want to leverage existing stuff ?
E.g.  leverage something like [openResty](https://openresty.org/en/) or reuse the [genericApi server from Kubernetes](https://godoc.org/k8s.io/kubernetes/pkg/genericapiserver)

Since this all about microservices and DRY I'd try not to reinvent the wheel ;-)

**Comment by jokeyrhyme** [comment]
Another approach could be to allow fission to extend k8s, so that functions and routes are just new entity types within k8s, governed  by the same access controls as pods, etc

**Comment by seriousme** [comment]
Which is another (even better ?) form of reuse :-)

I can imagine that if you run the k8s cluster yourself this is the preferred route, if you are just one of the tennants then I can imagine the owner is not keen on having others messing with his api server. Or is it possible to isolate extensions ?

**Comment by cwbeitel** [comment]
Maybe until the fission admin API has authentication it would be helpful/preventative for more novice users to have a note in the README to that affect given pods have kube admin sa credentials available to fission envs launchable through the API (unless I'm misunderstanding that). Maybe that people should be running in a private network space until beta?

**Comment by ajbouh** [comment]
What's the recommended network setup for securing a fission deployment?

**Comment by soamvasani** [comment]
Install with the helm chart with `serviceType` set to `ClusterIP`. Use a local `kubectl port-forward` to set up a localhost port that forwards to your controller port: `kubectl -n fission port-forward $(kubectl -n fission get pod -o name|grep controller|cut -f2 -d'/') 8888`

Then set $FISSION_URL to point to `http://localhost:<the port that kubectl outputs>`.

(We're working on making this the default and on automating the port-forward inside the fission cli.)

**Comment by soamvasani** [comment]
The default behaviour is now (i.e. 0.6.0 onwards) what's decribed in the comment above. The fission API is a cluster-internal service, and the CLI creates a temporary portforward on localhost to talk to the API.
