### ISSUE TITLE
Helm chart and CRDs

### ISSUE THREAD

**Issue by arbourd** [fission/fission#2245]
Any reason why the Helm Chart doesn't create the CRDs?

**Comment by sanketsudake** [comment]
Hey @arbourd, Currently when we call `kubectl apply` it has a limit of specific bytes being passed. 

```
Too long: must have at most 262144 bytes
```

It especially applies to Environment CRD https://doc.crds.dev/github.com/fission/fission/fission.io/Environment/v1

When Helm chart creates CRDs it does `kubectl apply` kind of operation so it fails.

CRDs operations are done with `kubectl create`, `kubectl replace` and `kubectl delete` in Fission's case to work around with above limitation.

Due to this, we have to manage CRDs outside of the helm chart.

I know a few projects which face similar issues due to limitations in `kubectl apply` Eg. https://github.com/strimzi/strimzi-kafka-operator

**Comment by arbourd** [comment]
That answers my question so I'll close this. Thanks!
