### ISSUE TITLE
Support for query parameters in fission route

### ISSUE THREAD

**Issue by sanketsudake** [fission/fission#2271]
**Fission/Kubernetes version**

<pre>
$ fission --version
$ kubectl version
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

Currently, if I want to call a function with query parameter for Fission, seems like fission cant handle it.

```
svc-router/hellofunc?queryparam=123
```

I need to pass it as part of the URL only with regex.

`hellofunc /{html:[a-zA-Z0-9\.\/]+}`

We may need support for https://pkg.go.dev/github.com/gorilla/mux#Router.Queries

**To Reproduce**

Create a function with query params support and try to call it via route. Router reports path not found.

**Expected result**

**Actual result**

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by praddy26** [comment]
Hello @sanketsudake 

I would like to work on this issue, if it's still open.

**Comment by sanketsudake** [comment]
Hey @praddy26 Feel free go ahead with it.

**Comment by sanketsudake** [comment]
Slack conversation reference https://fissionio.slack.com/archives/C3LUX6BBP/p1637677938049800

**Comment by shubham-bansal96** [comment]
> **Fission/Kubernetes version**
> 
> $ fission --version
> $ kubectl version
> **Kubernetes platform (e.g. Google Kubernetes Engine)**
> 
> **Describe the bug**
> 
> Currently, if I want to call a function with query parameter for Fission, seems like fission cant handle it.
> 
> ```
> svc-router/hellofunc?queryparam=123
> ```
> 
> I need to pass it as part of the URL only with regex.
> 
> `hellofunc /{html:[a-zA-Z0-9\.\/]+}`
> 
> We may need support for https://pkg.go.dev/github.com/gorilla/mux#Router.Queries
> 
> **To Reproduce**
> 
> Create a function with query params support and try to call it via route. Router reports path not found.
> 
> **Expected result**
> 
> **Actual result**
> 
> **Screenshots/Dump file**
> 
> $ fission support dump
> **Additional context**

I have verified few scenario to replicate this issue, but couldn't replicate it. Fission now support query parameter routing.
https://fission.io/docs/usage/languages/python/#create-a-simple-function-in-python

One thing to make sure specially in python is, if your function is expecting a query param then it is necessary to provide query param when you hit url to your function . Otherwise you will get 500 internal server error.

While this is not the case with Golang, if you don't provide query param then there won't be any issue on the same.
