### ISSUE TITLE
Two fission releases can't be installed via helm into the same cluster

### ISSUE THREAD

**Issue by airhorns** [fission/fission#2291]
**Fission/Kubernetes version**

1.15.0, 1.21

**Kubernetes platform (e.g. Google Kubernetes Engine)**

GKE

**Describe the bug**

For complicated deployments of fission, it is convenient to deploy a whole second copy of fission as a staging environment. This is useful for testing out version upgrades or new configurations alongside the existing setup that is working fine. Right now though, the helm installation method prevents this.

The fission helm charts create a `ClusterRole` resource, which causes conflicts when you try to install the helm chart twice into two separate namespaces. The first helm install goes fine, but the second one fails with an error like this:

```
inspector ~/C/global-infrastructure (main*) ➜  helm upgrade fission-canary --version 'v1.15.0' --install --create-namespace --namespace fission-canary fission-charts/fission-all -f charts/fission-canary.yaml
Release "fission-canary" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "fission-cr-admin" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "fission-canary": current value is "fission"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "fission-canary": current value is "fission-production"
```

**To Reproduce**

Install fission twice with as two different helm releases with two different `values.yaml` into two different namespaces.

**Expected result**

Helm install works fine for the second installation and as little as possible is shared between the two installations.

**Additional context**

I think this is a somewhat common issue for helm charts which create cluster wide resources like `ClusterRole`s. I think there is a way to get helm to check if the cluster-wide resource exists already which would allow this to work outlined here: https://stackoverflow.com/questions/65110332/clusterrole-exists-and-cannot-be-imported-into-the-current-release, but also, is there a way we could use normal `Role` resources instead so that two installs wouldn't be sharing the same resource?

**Comment by sanketsudake** [comment]
I am exploring a few approaches to this.

1. Getting rid of cluster role and cluster role bindings and use roles only. 
2. Make creation or use of cluster role & cluster role binding optional

----

Currently, we use the following ClusterRole and ClusterRoleBindings:

ClusterRole

1. secret-configmap-getter 
2. package-getter
3. fission-cr-admin - Crucial role used by all fission components 

ClusterRoleBinding

1. fission-cr-admin bound to fission-svc service account
2. secret-configmap-getter  used to find secrets and config maps to function pods
3. package-getter used retrieve packages by function pods

---

In the current scenario, fission-cr-admin is an important role used to monitor fission resources created across namespaces.  We can't think of converting it to Role.

We can explore if `secret-configmap-getter` and `package-getter` can be converted to Role.
I am trying to small POC to play around with this.

`fission-cr-admin` we will have to skip the creation of cluster role if already exists or the Fission operator would have different options available via helm chart.

----

As a quick fix, we can certainly think of providing flags so that users can choose to create RBAC resources, skip which can collide.

----

One possible issue on side note, we should be aware of should be CRDs(Custom Resource Definitions) management. As CRDs are managed outside the helm chart and one cluster can only have one set of fission CRDs. So if there are any changes in CRD, we may see issues in two Fission versions on the same cluster. We need to improve our CR versioning if any changes in CRDs.

**Comment by airhorns** [comment]
Thanks @sanketsudake !!
