### ISSUE TITLE
Docker containers as functions

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#235]
This issue tracks a feature request to run docker container images as functions.

Depends on #193.

**Comment by yqf3139** [comment]
In fission, we assume that environment specific containers work in the same pattern. Two or three http endpoints are exposed to receive the function specialization request, function call requests and metrics requests in the future.

To use docker containers as functions, there are maybe two patterns. The first is that it works like the common fission environment containers but specialization is not needed. It listens function calls on a http endpoint. The  second is that it reads request from env or command line variables, writes the response to stdout or other services and then exits. So that is one request per function instance. In this case, we need to define the exchange protocols(translate triggers events into the env variables, and translate the response for the client).

**Comment by erwinvaneyk** [comment]
As a step towards this goal, currently we have the binary environment which supports the execution of any Linux executable (@yqf3139's solution 2).  Although I think docker container execution should be discouraged, as it is by definition not following the operation abstraction of FaaS, I can imagine that there are situations where it is unavoidable.

I like @yqf3139 idea of having 'already' specialized environments, as it fits in the already existing idea of having more configurable environments (like environments with multiple specializations or environments). 

The easiest way to allow execution of arbitrary this is to create an image which is more or less the fetcher + binary env. An alternative would be is to provide binaries of the fetcher + binary env which users can add to their own images in order to implement the environment interface.

So to be concrete for this issue we need the following:
- [ ] Implement a way to provide configurable environments, allowing for the immediate specialization of an environment.
- [ ] Create an image or multi-platform binary that implements the environment interface.
- [ ] Way for users to use this binary/image in their own images.

**Comment by soamvasani** [comment]
> Although I think docker container execution should be discouraged

FaaS is a poorly defined term, and we should evolve with use cases.

There's definitely cases where images-as-functions is useful. E.g. people who already have a process in place to output docker images, but want the resource utilization and UX improvements they can get from fission.

> fetcher + binary env

The arbitrary binary use case is very different from the arbitrary image use case. There is no need for fetcher in this case, the function is already in the image.

> So to be concrete for this issue we need the following:

See #193 for a simpler and more direct approach. There's no need to make environments more complex; we can allow the user to specify a docker image as a function and short-circuit most of the poolmgr. Fetcher will not be used at all. Such functions would have no environment.

**Comment by erwinvaneyk** [comment]
Agreed, fetcher is irrelevant for this use case indeed.

**Comment by panigrahis** [comment]
As of now Fission is FAAS solution... Adding this feature would take it towards the larger superset of Serverless solution... In my opinion this is a must have feature...

**Comment by erwinvaneyk** [comment]
@panigrahis interesting, what is your view on the difference between Serverless vs. FaaS? And how do docker containers fit into that picture?

**Comment by rapitable** [comment]
I just want to be the first one to coin the term IaaFaaS :-)
Also I'm interested to see where this discussion goes as I'm not yet clear on the concept. 

Are we talking about an image whose Dockerfile CMD is a once-only command that expects the 'function' input, then we somehow get the output out after execution is complete? In this case calling the function would presumably just mean scheduling pod for the image with some state (e.g. 'env.value'?) containing the function input?

Or are we talking about an image whose Dockerfile CMD already runs a service (like node)? And Fission just coordinates scheduling a pod when needed and deleting it when it hasn't been called for a while?

**Comment by soamvasani** [comment]
@rapitable @yqf3139 I'm not 100% sure whether we should do one of those or both. I can imagine use cases for both, but I'd like to know what the people who want this are more interested in -- short lived CGI-style commands-as-services, or Fission management of containers running servers in them?

@erwinvaneyk @panigrahis while the whole discussion of serverless vs faas definitions is interesting, it doesn't feel directly on-topic here. Would y'all mind taking it to slack or twitter please? Thanks!

**Comment by dmlond** [comment]
IMHO the 'short lived CGI-style commands-as-services' that fission currently supports is a really useful solution. I dont see how executing docker containers would work in this paradigm given the constraints of an http request/response cycle.  

That being said, I can see 2 other potential architectures in a serverless context:
- request -> queue -> execute function
- websocket with input -> input queue -> executes function and sends output/error to output/error queues -> websocket response

Both of these architectures would work well with the extra overhead of launching a docker container of a specific image, as it is already running as a background process. The image would most likely need to have an ENTRYPOINT associated with it, or the function creator would need the ability to specify the command at function definition time through the fission api. 
The ability to launch docker image containers opens up the flexibility of using things like source_to_image to build out function images in an automated/reproducible fashion.
