### ISSUE TITLE
Support for compiled languages

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#24]
To support Go, Rust, and other compiled languages, we'll need a separate build step.  This should be triggered at function create/update.

Environments will need a link to an image that will have the compiler and other tools (such as dependency managers).

We will need to figure out a way to specify dependencies for functions.  Maybe a new fission resource type for a dependency spec, and a way to associate that resource with functions.

**Comment by isubuz** [comment]
When you say "a separate build step", do you mean a step which creates the executables and then load these executables when the function is _triggered_? 
I guess for Java which supports dynamic loading, the functions could be loaded from source, similar to what is done for Python? I guess the performance hit happens only the first time the class is loaded into memory.

**Comment by soamvasani** [comment]
> When you say "a separate build step", do you mean a step which creates the executables and then load these executables when the function is triggered?

The functions would be compiled when they are created (or updated); the result of the compilation would be cached. That way we don't add the compilation time to the request path. 

Then, on request, the compiled function (.so/go plugin file/jar file) would be copied into the generic pod, loaded, and run.  We haven't yet measured the performance of loading a Java class dynamically, but yes, the performance hit of loading will only affect the "cold start" of a function.

**Comment by GiorgioG** [comment]
How about some documentation as to how to add language support?  I'm particularly keen on adding C# / .NET Core support and would happy to contribute if only I had an inkling into what it involved.

**Comment by soamvasani** [comment]
Hi @GiorgioG, there is an early version of a C# .NET environment contributed by @ktrance.  If you're interested in contributing to that, please take a look at [environments/dotnet](https://github.com/fission/fission/tree/master/environments/dotnet).

That environment compiles code on cold-start, which is a short term solution until this issue is resolved.

There isn't yet documentation for this, because we don't yet have compiled language support ready.  That work is being designed and specified in [Documentation/wip/environments-v2.md](https://github.com/fission/fission/blob/master/Documentation/wip/environments-v2.md).

**Comment by Marak** [comment]
Compiled languages are tricky for faas. We've done some work on implementing these in hook.io. Have been considering adding support to https://github.com/stackvana/microcule, but it's not been a heavily requested feature.

The service should build fresh the first time and then you'll need a cache to store the compiled source code and then a smart way to know when to invalidate the cache. Compilation errors need to be piped back to the client in real-time.

**Comment by ktrance** [comment]
@GiorgioG, @soamvasani , I am currently looking at giving access to the request information to the function but in flat .Net types without bleeding Nancy objects in as a dependency. 

I will probably create pull request tomorrow(small code change) for that but if you have knowledge of light weight logging frameworks on dotnet, especially a dependency free facade around it would be awesome.

**Comment by Marak** [comment]
Been doing a bit of development on this and it seems you'll want a mutually exclusive lock on the compilation step for services.

I was considering implementing a queue to hold pending requests until the compilation is complete, but I think it will be a cleaner design to simply respond with a `202 Accepted` response for any incoming requests that come in while the binary is compiling.

I'm also looking into creating `shasum1` hash of service contents for the created name of the binary ( seems like a good idea ).

**Comment by Marak** [comment]
Hello all. cc @soamvasani and @ktrance 

I wanted to chime in with an update for compiled language support at https://github.com/stackvana/microcule. Since these two projects have a bit of overlapping functionality, I thought it would be best so share.

  As of version 5.x.x, `microcule` now has support for hosting functions written in compiled languages ( or any arbitrary binary for that matter ).

  Current supported compiled languages: `gcc`, `golang`, `java`, `rust`. We also have working examples creating streaming HTTP microservers using `echo`, `ls`, and `tail -f`.

  First, it's important to note that `microcule` is just a collection of HTTP middleware plugins, so we've added a new plugin `compile` to compliment our `spawn` plugin. If we were to call the `compile` middleware, we would either get a compiled binary ready to run, or a STDERR and STDOUT with a non-zero exit code. [Here is an example of spawning a gcc service with express.js](https://github.com/Stackvana/microcule/blob/master/examples/express-compiled-languages.js)

  For the new default behavior of the `spawn` middleware, we added integrated support for `compile`. This means we have configurable behavior for when a compiled language is built, with the default behavior being it compiles in response to the first HTTP request ( cold start ). You could also `compile` and validate before starting any services or receiving any requests. Technically, once a service is compiled, you could use `microcule` to spawn it as an arbitrary binary ( which means the language choice / `compile` code path would be ignored)

  In implementing compiled languages / build step / real-time compilation / arbitrary binaries, we did the following:

   - Default `spawn` configuration is to **not** `compile` service until it's first requested ( compiles on first incoming request )
   - Added mutually exclusive lock for compilation of services ( based on shasum )
     - Subsequent requests are served `202 Accepted` until service compiles
     - State of lock is stored with Key-Value Provider pattern ( in-memory or Redis client )
     - Compilation errors are sent back to the original request of the service
     - We potentially could store the compilation error somewhere with Provider pattern ( since we are already tracking build status )
   - After initial compilation binary is on local file-system and somewhat cached forever
   - File-system and Provider Cache uses `shasum` of source code file as key ( very useful as this sha should be universal across systems )
   - Compiled services are immutable ( same service code will not recompile on system unless cached binary is deleted )


  The biggest reason we chose to allow such a high level of configuration is mostly based on the fact that our elastic worker pool at [hook.io](hook.io) is stateless. `microcule` don't have any concept of registering services, pods, or auto-scaling. This means we need to be able to send source code to a running worker and have it execute that code. For our use-cases, caching the compiled binary and using a mutually exclusive lock for the build step is necessary, as we have no idea if the service has been executed before on the worker.
  
  Hope this information helps a bit! Looking forward to seeing how you will implement build step for compiled languages in `fission`.

**Comment by markfink** [comment]
hi, please excuse my ignorance since I am new to open source serverless. I was looking for a fission sample in golang but I could only find dotnet, nodejs, php7, and python samples. My assumption was that it must be easy to support golang since it is implemented in go. I noticed people asking for other technologies.
With Go1.8 plugin support I assume that this is definitely possible. Do you have concrete plans to support golang? What is your timeframe?
I am a go programmer so can I help with something to speed things up?

**Comment by nouney** [comment]
@markfink

 See PR #125

**Comment by ezoerner** [comment]
I would like to have this feature so that functions can be implemented in **Haskell**.
Instead of having Fission compile the code, would it make sense to support deploying a function as a Docker container with the already compiled code in it? This would actually allow the function to be written in any language that compiles to a native binary.
I can see how this would go against the ease-of-use goal for Fission ("just the code"), but I think it would be a nice alternative as a general purpose environment.

**Comment by erwinvaneyk** [comment]
@ezoerner it is indeed a reasonable idea. This approach is taken by other initiatives in the serverless area, such as https://github.com/kubeless/kubeless as the principal approach. However there are also some downsides to such an approach, such as the startup cost of a container and (as you already mentioned) it isn't "just code" anymore. 

That said, there is certainly room for a more generic environment or approach to complement the existing more specialized environments in Fission.

**Comment by 7h3kk1d** [comment]
Seems like the goal would be to have a flexible way to integrate any type of event listening program. Making the mechanism as flexible as possible also allows  better future opportunities for integrating with current build pipelines and deployment tools.

**Comment by soamvasani** [comment]
@ezoerner There's been some discussion of running images as functions; I think we'll most likely end up implementing something like it after beta.  See also #193.

@7h3kk1d fission decouples event triggers from how functions are executed.  More flexible event triggers are covered elsewhere, such as #194.  

This issue is a subset of Environments v2 #103, which covers compiled languages, and #193, which would allow container images as functions. So let's close this issue in favor of those.
