### ISSUE TITLE
fission settings to avoid running as root across fission components and functions pods

### ISSUE THREAD

**Issue by coopstah13** [fission/fission#2401]
**Fission/Kubernetes version**

fission 1.15.1
kubernetes 1.20

**Kubernetes platform (e.g. Google Kubernetes Engine)**
k3s

**Describe the bug**

The fetcher container runs as root, and as such writes files as root, which requires functions to run as root.

**To Reproduce**

Run any sample function

**Expected result**

The function runs as a non-root user.

**Actual result**
The function runs as the root user

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

It is not acceptable to run containers as root, generally. Fission should be able to operate without root. Minimally the files extracted by fetcher should be readable by non-root user (this is not the case). Through my environment configuration I have marked the pod as `runAsNonRoot` and also specified `runAsUser`, and `runAsGroup` with success.

**Comment by sanketsudake** [comment]
Hey @coopstah13 Most of the users customize these settings as you have done. Definitely worth having it in default helm chart as good security practices.

**Comment by sanketsudake** [comment]
## Primary solution

With PR https://github.com/fission/fission/issues/2401 Fission user can enable security context across fission components. This is not enabled by default.

Fission components securityContext settings
```
executor.securityContext.enabled: true
router.securityContext.enabled: true
buildermgr.securityContext.enabled: true
controller.securityContext.enabled: true
kubewatcher.securityContext.enabled: true
storagesvc.securityContext.enabled: true
```

This still leaves Fission functions and builder pods.
Currently if user customised podSpec in Fission environment runtime and builder, they can mention podspec security context and customise.

## Extended solution

We are also thinking of combination for different setup of users as more simplified solution.
We have target users:

- Fission administrators

We can define a pod security context for function pods and builder pods which can be enabled at helm chart level.
If enabled at Fission installation level,  all function pods and builder pods created from fission would have security context.

- Function developers

We can add a flag in fission function create and env create cli so that security context would get populated in fission spec.

Please refer if you want to enable securityContext as of now.
https://doc.crds.dev/github.com/fission/fission/fission.io/Environment/v1@v1.16.0#spec-builder-podspec-securityContext
https://doc.crds.dev/github.com/fission/fission/fission.io/Environment/v1@v1.16.0#spec-runtime-podspec-securityContext

Could be something like

```
    runAsNonRoot: true
     fsGroup: 10001
     runAsUser: 10001
     runAsGroup: 10001
```

Kubernetes docs:  https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1


cc @coopstah13
