### ISSUE TITLE
Function pod immediately terminates after first execution and don't honor idle timeout

### ISSUE THREAD

**Issue by nunojca** [fission/fission#2451]
**Fission/Kubernetes version**
<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1
server:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:35:50Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
n
</pre>

**Kubernetes platform:**
Docker Desktop

**Describe the bug**
Function pod immediately terminates after the first requests and don't honor idle timeout. This happens both on NewDeploy and Container Function after update of the function idle timeout.

**To Reproduce**

- Create environment with minscale 0 and default idle timeout.
- Create function (e.g. go hello world) with NewDeploy executor.
- Update function idle timeout to a different value from default, either via CLI or CR.
- Test function
- Check function pods

**Expected result**
It was expected the function pod to honor the idle timeout.

**Actual result**
The function terminates immediately after function execution. In some occasions the function doesn't execute and gives an error.

**Screenshots/Dump file**
<pre>
Error: Error calling function f1: 500; Please try again or fix the error: error sending request to function
Error: Error getting function logs from controller: error getting logs from controller, status code: '500'. Try to get logs from log database.
Error querying logs: Post "http://127.0.0.1:34125/proxy/influxdb?db=fissionFunctionLog&params=%7B%22funcuid%22%3A%22d6c80386-802b-4ade-906b-ef47f7ab2c1a%22%2C%22time%22%3A0%7D&q=select+%2A+from+%2F%5Elog%2A%2F+where+%28%22funcuid%22+%3D+%24funcuid++OR+%22kubernetes_labels_functionUid%22+%3D+%24funcuid%29+AND+%22time%22+%3E+%24time++order+by+%22time%22+asc+LIMIT+1000": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[fission-dump_1654674530.zip](https://github.com/fission/fission/files/8859480/fission-dump_1654674530.zip)
</pre>

**Comment by sanketsudake** [comment]
Reference slack thread https://fissionio.slack.com/archives/C3LUX6BBP/p1654608636841329

**Comment by shubham-bansal96** [comment]
Hi @nunojca  
we are able to replicate this issue. Let me explain what's actually going on.

Initially when the function get terminates after the idle timeout and then user update the idle timeout of the same function in that case function get updated but with the new resource version.

I mean now the function have two same object but with different resource version. Since both object runs on go-routine so when user test the function after updating the idle timeout then function pod comes up for the new object(updated function) but due to first object that have old resource version and running on goroutine, that terminates the pod immediately.

We have identified this issue and we are working on it.
