### ISSUE TITLE
Impossible to get Python Http Headers from a function built with a package

### ISSUE THREAD

**Issue by voldor** [fission/fission#2483]
<pre>
$ fission version

client:
  fission/core:
    BuildDate: "2022-05-24T07:28:44Z"
    GitCommit: ed1e4a5c
    Version: v1.16.0
server:
  fission/core:
    BuildDate: "2022-05-24T07:28:44Z"
    GitCommit: ed1e4a5c
    Version: v1.16.0
$ kubectl version
Kustomize Version: v4.5.4
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**
i created a python function with an associated package for depedencies management 
When i try to get headers from the function i see no headers available 

**To Reproduce**

[ven-fun-average-tempV2.0.0.zip](https://github.com/fission/fission/files/9092356/ven-fun-average-tempV2.0.0.zip)
Fission.exe package create --name ven-fun-average-temp-py-v2-0-0-zip --sourcearchive ven-fun-average-tempV2.0.0.zip --env python --buildcmd "./build.sh"

Fission.exe fn create --name ven-fun-average-temp-py-v2-0-0 --pkg ven-fun-average-temp-py-v2-0-0-zip --entrypoint "main.main"

Fission.exe route create --function ven-fun-average-temp-py-v2-0-0 --url /ven-fun-average-temp-py-v2-0-0 --name ven-fun-average-temp-py-v2-0-0
curl -H "s3-region: euw" %ROUTER%/ven-fun-average-temp-py-v2-0-0

**Expected result**
All Headers Host: 10.42.173.125:8888
User-Agent: curl/7.79.1
Accept: */*
Traceparent: 00-0a20f12e4aa4a84ef067058a62cb488a-f476a4a139500a7b-01
X-Fission-Full-Url: /headers
X-Fission-Function-Name: headers
X-Fission-Function-Namespace: default
X-Fission-Function-Resourceversion: 22110821
X-Fission-Function-Uid: 56c2d907-9dbc-4edd-8420-098c041cbee6
X-Forwarded-For: 91.103.43.254, 10.42.1.18
X-Forwarded-Host: MyHost
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-My-Header: euw
Accept-Encoding: gzip
Connection: close

**Actual result**
All Headers Host: 127.0.0.1:8888
User-Agent: Go-http-client/1.1
Traceparent: 00-133b7d8f5174a75f645dfdbc40b624df-a9902c9a02638b48-01
Accept-Encoding: gzip
Content-Length: 942
Content-Type: application/json

<Response 20 bytes [200 OK]>
**Screenshots/Dump file**

[fission-dump_1657624795.zip](https://github.com/fission/fission/files/9092326/fission-dump_1657624795.zip)

<pre>
$ fission support dump
</pre>

**Additional context**
Fun tion created from windows

**Comment by shubham-bansal96** [comment]
@voldor 

Please change your code little bit in main.py file. Avoid printing all headers using print() function, instead of send all headers to resp. 
Currently in your code you are printing all headers and returning header "s3-region" only to resp, and that's why you are not able to see all the headers. Please have a look into my code(attached in ZIP folder) and try to modify your function similar to this.
![Screenshot from 2022-07-21 15-00-21](https://user-images.githubusercontent.com/62992590/180180810-45739cbb-89a5-45fd-b7e5-11566f912984.png)
[Python.zip](https://github.com/fission/fission/files/9158133/Python.zip)
