### ISSUE TITLE
Installation in different namespaces

### ISSUE THREAD

**Issue by pbochynski** [fission/fission#386]
Right now helm chart is working only with fission namespace. It is possible to install it in the different namespace, but mqtrigger will not work because router URL is not configured with a namespace. This is a small bug that can be easily fixed, but this is just the tip of the iceberg. 
Chart creates cluster roles and role bindings and uses other namespaces (fission-function, fission-builder) that prevent users from installing fission in the second namespace (the second installation will fail). 

Charts should be redesigned to install all components into single namespace provided by Helm. In this way, people can use k8s namespaces to isolate test and production ready functions in a single cluster.

**Comment by soamvasani** [comment]
This is a good use case to support. 

The reason we have these many namespaces in the first place is to allow users to specify resource limits separately for (a) fission controllers (b) fission functions and (c) fission builders. This allows fine-tuning and is probably something desirable for production use, especially in large organizations.

But, thanks to your issue and the recent discussion on slack, I'm thinking the simple case should be kept simple, and by default we should install into a single namespace. To do this, the following changes are needed:

 * The helm variables for namespaces (`functionNamespace` and `builderNamespace`) should default to `Release.Namespace`.
 * The templates should only create function and builder namespaces when they're different from `Release.Namespace`
 * All un-namespaced resources should have generated names, with labels/annotations indicating what install they're part of.  Currently I think the only un-namespaced resource we create are the cluster role bindings.

**Comment by janmedrek** [comment]
We've managed to create helm chart that installs fission in one namespace (according to your suggestions). Got rid of bindings for now as well - the installation with our chart completes successfully and we are able to install multiple instances within single cluster.

Everything seems to be working fine until environment creation, every service in the namespace is deleted (buildermgr, controller, influxdb, nats-streaming, poolmgr, router, storagesvc) - this renders fission unusable due to lack of communication.

We've also noticed that **only** services are affected, deployments stay intact.

Do you have any hints on where to start looking for the origin of this problem? Which part of fission may cause service wipe during environment creation?

**Comment by janmedrek** [comment]
Ok, I have made some progress but encountered another wall.

Environment creation resulted in deletion of services and some fission's deployments - this was caused by envwatcher that treated them as 'orphaned' (envwatcher.go, lines 207:239). I've decided to resolve it temporarily by commenting out those deletion features (assumed that I wont be orphaning my environments for a while).

Above actions allow for creating environment, functions and routers - everything seems to be working fine.

The problem I've found is that functions are not responding. Environment is fetched, like generic pool and service. Then it comes to choosing pods for the function - there it times out.

Do you happen to have any insights on what's the problem here?

Attaching logs, hope they may help.
poolmgr:
> kubectl logs -f poolmgr-1970358009-58n6b -n fission
2017/11/06 12:20:36 starting poolmgr at port 8888
2017/11/06 12:21:47 Creating pool for environment {nodejs  default /apis/fission.io/v1/namespaces/default/environments/nodejs 0e4c9399-c2ed-11e7-b523-080027cdaf32 980 0 2017-11-06 12:21:46 +0000 UTC <nil> <nil> map[] map[] [] [] }
2017/11/06 12:21:47 fetcher image: fission/fetcher:0.3.0, pull policy: IfNotPresent
2017/11/06 12:21:47 [{nodejs  default /apis/fission.io/v1/namespaces/default/environments/nodejs 0e4c9399-c2ed-11e7-b523-080027cdaf32 980 0 2017-11-06 12:21:46 +0000 UTC <nil> <nil> map[] map[] [] [] }] Deployment created
2017/11/06 12:25:20 [hello] Checking for cached function service
2017/11/06 12:25:20 [hello] No cached function service found, creating one
2017/11/06 12:25:20 [hello] getting environment for function
2017/11/06 12:25:20 [&{hello  default /apis/fission.io/v1/namespaces/default/functions/hello 1557a6e4-c2ed-11e7-b523-080027cdaf32 1038 0 2017-11-06 12:21:57 +0000 UTC <nil> <nil> map[] map[] [] [] }] getting env
2017/11/06 12:25:20 [hello] getting generic pool for env
2017/11/06 12:25:20 [hello] getting function service from pool
2017/11/06 12:25:20 [hello] Choosing pod from pool
2017/11/06 12:25:20 [map[unmanaged:true functionName:hello functionUid:1557a6e4-c2ed-11e7-b523-080027cdaf32 poolmgrInstanceId:VCZwowy6]] found 0 ready pods of 0 total
172.17.0.6 - - [06/Nov/2017:12:25:20 +0000] "POST /v2/getServiceForFunction HTTP/1.1" 500 45
2017/11/06 12:30:21 Error: 500: timeout: waited too long for pod to be ready

router:
> kubectl logs -f router-2783520960-g6swz -n fission
2017/11/06 12:20:47 Starting router at port 8888
2017/11/06 12:20:47 Syncing http triggers
2017/11/06 12:21:57 Syncing http triggers
2017/11/06 12:22:03 Syncing http triggers
2017/11/06 12:25:20 Not cached, getting new service for &{hello  default /apis/fission.io/v1/namespaces/default/functions/hello 1557a6e4-c2ed-11e7-b523-080027cdaf32 1038 0 2017-11-06 12:21:57 +0000 UTC <nil> <nil> map[] map[] [] [] }
172.17.0.1 - - [06/Nov/2017:12:25:20 +0000] "GET /hello HTTP/1.1" 500 32
2017/11/06 12:30:21 Failed to get service for function hello: Internal error - timeout: waited too long for pod to be ready
