### ISSUE TITLE
Allow url as source when creating functions

### ISSUE THREAD

**Issue by erwinvaneyk** [fission/fission#441]
Currently the example in the installation notes contains the following
```
...
$ curl -LO https://raw.githubusercontent.com/fission/fission/master/examples/nodejs/hello.js

$ fission function create --name hello --env nodejs --code hello.js
...
```

However the following...
```
fission function create --name hello --env nodejs --code https://raw.githubusercontent.com/fission/fission/master/examples/nodejs/hello.js
``` 
...will result in an error.

In contrast, in Kubernetes (and Helm) providing an url is allowed. To improve the UX, I propose that we add support for urls as well.

**Comment by life1347** [comment]
Here are things need to be done for who tries to take this issue.
1. Download file before creating the package for security concerns.
Previously, we can put URL in the archive and fetch code when compiling or serving. This approach is not that ideal because: (a) the file(s) URL points to may be unavailable after some time. (b) the possibilities that the target file was replaced with malicious code.

1. Retire `ArchiveTypeUrl`
https://github.com/fission/fission/blob/master/pkg/apis/fission.io/v1/const.go#L39
