### ISSUE TITLE
Golang build helper script not found

### ISSUE THREAD

**Issue by vincen7su** [fission/fission#457]
In the [Go examples](https://github.com/fission/fission/tree/master/examples/go), the build helper script is missing.
https://raw.githubusercontent.com/fission/fission/master/environments/go/builder/go-function-build

**Comment by erwinvaneyk** [comment]
Hey @vincen7su, thanks for the feedback 😁 ; that is indeed an issue looking at. The documentation does not yet reflect the recent introduction of the go builder environment. 

The builder environment ensures that you no longer need to use the manual `go-function-build`; it does it for you when you upload your Golang code. You can add a builder to your environment using the `--builder` argument.

There are a couple of errors in documentation looking at it quickly:
- [ ] https://github.com/fission/fission/blob/master/environments/go/README.md - the `Using the mage in Fission` misses the argument `--builder USER/go-builder`
- [ ] https://github.com/fission/fission/tree/master/examples/go - add builder to env creation similar to the first point `--builder fission/go-builder:1.8.1`

If you want, you can submit a PR to fix the issues above. Otherwise someone else could pick this up.
