### ISSUE TITLE
"newdeploy" executor backend user docs

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#470]

**Comment by vishal-biyani** [comment]
@life1347 and @soamvasani The first cut (This PR) is not perfect and more detailed documentation with a better structure coming in couple days - would you like to take this in 0.5 or remove it for now?

**Comment by life1347** [comment]
Since users can see the changes in CLI, so I think it's good that this doc gives the user a concept of what executor type is. How about adding some simple command line usage to the current doc and merge it? At least users can try this feature and give some feedback. Though the doc is not perfect enough, we still can improve it in next couple iterations.
