### ISSUE TITLE
HTTP request send to wrong Kubernetes pod

### ISSUE THREAD

**Issue by oif** [fission/fission#486]
Hi,
I found an issue about HTTP Trigger function.  `fission version 0.4.1`

Steps
1. Create an env with only single runtime pod(like workflow env)
2. Deploy some functions with HTTP trigger on this env
3. Delete the env pod or this pod killed for some reasons (auto recover due to deployment controller)
4. curl this HTTP trigger
5. Check router logs find out request is forwarded to old pod IP

I'm not quite sure this issue is caused by Executor or other components

**Comment by erwinvaneyk** [comment]
Hi @oif thanks for this issue. Yesterday I noticed similar behavior with the workflow environment as well. It doesn't seem related to the HTTP trigger, just triggering the function through `$FISISON_ROUTER/fission-function/<fn>` causes the same issue. I am not sure if this

I am not sure if this is specifically related to the workflow environment or whether other environments also exhibit this behavior.

cc @soamvasani

**Comment by ananichev** [comment]
@oif @erwinvaneyk I faced the same issue. Seems the problem is in the function's cache. When a pod is created its address is put to the function's cache. And when you delete the env pod or this pod killed seems cache is not cleared. And the rotuer tries to proxy request to a died address.

**Comment by soamvasani** [comment]
Thanks for the report @oif.

@erwinvaneyk this is unrelated to workflows.

@ananichev Yes, that's exactly it. The caches in both executor and router(s) keep the pod info for a minute or so, and for that duration requests are proxied to the dead IP.

To fix this there are a couple of changes we can make:
 1. watch for pod status changes and invalidate the caches in executor and router
 1. retry on connection errors 

The first change is definitely something we should do, but it doesn't solve all errors (it's still racy, since the invalidation might occur after a request is proxied to a dead IP).  

The second change doesn't suffer from that racy-ness, but may cause functions to be executed twice; this may be undesirable and probably shouldn't be the default.  This retrying behaviour would need to be controlled by some sort of new flag in the function and/or trigger spec.

**Comment by smruthi2187** [comment]
The CI runs are failing. needs more testing.

**Comment by smruthi2187** [comment]
Finally, CI runs did pass with this change and a subsequent change to prevent releasing idle transport connections.
