### ISSUE TITLE
Setting Capabilities and/or Security Context for Function Containers?

### ISSUE THREAD

**Issue by joshuabuildsthings** [fission/fission#556]
## This is a question & potential feature request, not a bug report.

I was wondering if it's possible to set capabilities for function containers at configuration time? It looks like it may be possible to do this via the Spec Apply method of configuring a function.

[Function build via Spec Apply Example](https://github.com/fission/fission/tree/master/examples/spec-example)

Is the case? If not, is it possible to extend Fission to support this functionality?

## Desired Outcome
Functions built via Spec Apply would respect Kubernetes Security Context settings; such as adding NET_ADMIN capabilities to the function container.

[Configure a Security Context for a Pod or Container | Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)

**Comment by soamvasani** [comment]
Great question, @joshuabuildsthings !  With #413 we're getting the ability to set an arbitrary Kubernetes Container spec for the environment.  This will allow setting up a security context at the environment level.  A function would then use that environment and inherit the Container object into the PodSpec.

It's not quite exactly what you asked for -- because a you'd want to set a security context at the function level too.  So I'll keep this one open for that purpose.  We should be able to get that working by adding a SecurityContext to the Fission Function CRD and having that override the Pod's SecurityContext (we'll use the [newdeploy executor backend](https://docs.fission.io/0.6.0/concepts/executor/) for that).

**Comment by joshuabuildsthings** [comment]
Thanks for the quick reply @soamvasani !  I'm excited to hear about the functionality #413 and will watch for it to be merged into a release. It's close enough to my desired functionality that I can fully evaluate Fission for my use case.

As for the proposal to add a SecurityContext to the Function CRD, I think that would definitely address my use case and add a useful feature to Fission.

Thanks again!

**Comment by joshuabuildsthings** [comment]
@soamvasani - Saw #413 get merged into 0.6.1, but couldn't find any documentation on how to use it. Can you please point me in the right direction?

**Comment by justinbuzzni** [comment]
@soamvasani 
kubectl edit environment python

I tried that config. however I failed. 
How can I add   
'''securityContext:
    privileged: true''' 

spec:
  TerminationGracePeriod: 360
  builder:
    command: build
    image: fission/python-builder:latest
  keeparchive: false
  poolsize: 2
  resources:
    limits:
      cpu: 80m
      memory: 128Mi
    requests:
      cpu: 40m
      memory: 64Mi
  runtime:
    functionendpointport: 0
    image: fission/python-env:latest
    loadendpointpath: ""
    loadendpointport: 0
  securityContext:
    privileged: true
  version: 2

**Comment by life1347** [comment]
It's now resolved by add podspec to env spec file. For details, see https://blog.fission.io/posts/fission_pod_specs/.
