### ISSUE TITLE
Fission CLI / client clean separation

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#583]

**Comment by rapitable** [comment]
I am submitting a PR that is the first step towards separating CLI and non-CLI functionality in the client `github.com/fission/fission/fission`.

## End goal

- Package `main` (existing)
 - Only job is to expose the CLI, take raw user command line input and marshal it into format suitable for consumption by non-CLI dependent library code (`lib`)
 - As such it contains only `urfave/cli` dependent functionality
- Package `lib` (new)
 - Exposes functionality to be consumed by either the existing CLI or by developers wishing to import the `lib` package in their own projects and interact with their fission cluster programmatically
- Acts as an abstraction layer on top of the raw fission API (`github.com/fission/fission/controller/client)`, to avoid developers having to understand and interact with the low level raw Function CRD API or re-implement much of the logic in this package in their own code
 - Contains all and only non-CLI dependent code, including input validation, creation of CRDs and interaction with the controller client.

## Done so far

So far FnCreate, FnList and FnDelete have been refactored. 
Work done so far:

- Create new lib package
- Export a CreateFunction function (with a generic, non-cli-based CreateFunctionArgs struct)
 - Change the cli FnCreate to simply build the CreateFunctionArgs and call CreateFunction with it
 - Refactor validation for the above so it is decoupled from CLI flags and uses `multierror`
- Take the same approach with FnList and FnDelete
- Move all other functions without dependency on CLI from main package into the new `lib` package and export them
- Refactor much of the error handling to return errors up the stack instead of calling os.Exit (for non-yet-refactored code, where not in CLI mode, do not exit but write a warning that further refactoring is required)
- Improvements to logging
- Clarify the requirements for arguments code vs src vs deploy (exactly one) and validate that these have been correctly used
- For `lib` mode, additionally allow code to be passed as a literal string instead of a file path
- Fix an issue with the DownloadToTempFile handling of temp files for url archives

## Still to do

- Refactor all other CLI commands in the same way as above
- In the meantime, contributors should `return` a `FailedToError` instead of calling `CheckErr`

## Library usage

Have tested usage as a library from another project. E.g.:

```
import (
	fission "github.com/fission/fission/fission/lib"
)

myclient := fission.GetClient(os.Getenv("FISSION_URL"))
createFunctionArg := fission.CreateFunctionArgs{
	FnName:         myname,
	EnvName:        myenv,
	CodeLiteral:    mycodestring,
	SrcArchivePath: myarchivepath,
	EntryPoint:     myfunctionname,
	Client:         myclient,
}
err = fission.CreateFunction(&createFunctionArg)
if err != nil {
	//...
}
```

**Comment by life1347** [comment]
Track by #1189
