### ISSUE TITLE
windows cli hangs while connecting to fission api or router

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#684]
It sounds like our portforwarding tricks don't work correctly on windows.  Needs further investigation.

**Comment by thejosephstevens** [comment]
Quick update, I'm finally back to working on this. I got hung up for a week swapping from a broken minikube VM to GKE, but I'm back on the horse now. Also, fwiw, I confirmed the port-forwarding issues aren't related to a remote cluster vs local minikube.

For doc purposes, I'm running Windows 10 version 1803, fission 0.7.2, kubernetes 1.10.2-gke.3, kubectl 1.9.7, and helm 2.9.1.

The current observed behavior is, when running a command like `fission env create...`, the command hangs indefinitely. Verbosity level 2 reveals that it stops doing anything after setting up the port forward to the fission api, and log fetch reveals that no communication ever actually gets to the API. I have a hunch that the port forward command is taking over the shell and blocking any further commands. I'm going to do a bit of debugging, but I think what's going to need to happen is to force the port forward to run in a second shell.

**Comment by thejosephstevens** [comment]
#715 has fixed this issue on my machine. I discuss the issue at length in the PR, but the gist is that a makeshift locking mechanism is written in the `findFreePort()` code that attempts to generate a file with colons in the name, which is not allowed in Windows. I have removed that code because the lock shouldn't be needed in Go 1.10. As a result though, this change will necessitate a Go minor version bump from 1.9 to 1.10. I recommend checking out the PR if you're interested in the longer explanation.

**Comment by life1347** [comment]
Close due to aged. Feel free to reopen it.
