### ISSUE TITLE
NewDeployment - Package update issue in 0.8.0

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#723]
After 0.8.0 release there is an issue with package update for new deployment executor functions which was seen consistently after multiple retries. (Log of failure: https://api.travis-ci.org/v3/job/388178258/log.txt) 

The same test has worked in immediately before builds (https://api.travis-ci.org/v3/job/387779126/log.txt)

This issue is to investigate & track the same

Currently following tests are failing consistently:

```
--- PASSED /test_fn_update/test_resource_change.sh
*** FAILED /test_fn_update/test_nd_pkg_update.sh
*** FAILED /test_fn_update/test_configmap_update.sh
*** FAILED /test_fn_update/test_secret_update.sh
--- PASSED /test_fn_update/test_poolmgr_nd.sh
--- PASSED /test_logging/test_function_logs.sh
```

**Comment by smruthi2187** [comment]
I think this is why tests are failing on our CI cluster. Referring to this log : https://api.travis-ci.org/v3/job/389024752/log.txt for the explanation.
1. First, a function, (in this log): hellopython-360269385 is created with executor type NDM. The resource version  ends up being : 41632529 . Also a service, hellopython-360269385-usbzmidi gets created with this selector :  
```"selector": {
                    "environmentName": "python-358862774",
                    "environmentUid": "5494865e-69e6-11e8-91db-42010a80010f",
                    "executorInstanceId": "usbzmidi",
                    "executorType": "newdeploy",
                    "functionName": "hellopython-360269385",
                    "functionUid": "54a90c0e-69e6-11e8-91db-42010a80010f"
                },```
2. Now, when we invoke the function at route : /hellopython-360269385, everything works as expected. 
3. Next, Function gets updated to have new code ( from hello world to hello fission ). The resource version ends up being 41632617.
4.When we invoke the function at route /hellopython-360269385, router does recognize the different resource version and requests executor for a new service. New pod is spun up with the latest code. the old pod is still terminating. But the service url returned to router remains the same : hellopython-360269385-usbzmidi(as expected). 
5. Now, router makes a http request to this service url hellopython-360269385-usbzmidi. But since the old pod is still terminating, the service _is_ _still_ routing to old pod ip that is terminating. So the response received is “hello world” instead of “hello fission”.

I ran a few tests on CI, where I waited for old pod to get deleted fully and then invoked the function with the http request, everything worked correctly. I.e. I did get “Hello Fission”

**Two solutions i can think of**, 
1. we can update the service to have selector of resource version of function pod inside `fnUpdate` function of `newdeploymgr.go` after we do a `deploy.updateDeployment`. ( this means when we do a deployment.update, we need to wait to grab the new resource version, attach it to pod labels and then update service object to include this label in the selector.)
Or, 
2. For environments that are used by new-deploy functions, the **envGracePeriod** should always be 0 so the old pod gets deleted as soon as the delete request is made.

Now, I dunno how this test worked all this while. May be the old pod was getting deleted faster ( even before we issued curl request for the updated function ) so we never ran into this issue.

**Comment by vishal-biyani** [comment]
Based on findings above and PR https://github.com/fission/fission/pull/730 proved that grace period made the bug disappear - but the underlying problem is something else.

Once update to function code happens, the old pod goes in terminating state and new pods comes up almost within next 10-20 seconds. The terminating pod remains in that state for durartion of grace period (6 minutes as from last tests)

```
$kubectl get pods -w -n f-func-e7675c -o wide
NAME      READY     STATUS   RESTARTS                                  AGE  IP
hellopython-794508904-i4iwiygr-5b86dc5cf8-4nlck  2/2  Running  0       1m   10.52.5.150
hellopython-794508904-i4iwiygr-d97c9767-5pclb    2/2  Terminating   0  1m   10.52.3.106
```

The endpoint is almost instantly populated with new POD IP address (In some cases it takes a second or two, but gets populated pretty fast): 

```
2018/06/08:10:46:05 Updating function with updated package
package 'test-deploy-pkg-zip-k7hr' updated
function 'hellopython-794508904' updated
2018/06/08:10:46:05 Waiting for deployment to update
Doing an HTTP GET on the function's route
Checking for valid response
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13    0    13    0     0      0      0 --:--:--  0:00:15 --:--:--     3
Resp Hello, world!
Name:         hellopython-794508904-i4iwiygr
Namespace:    f-func-e7675c
Labels:       environmentName=python-793686619
              environmentUid=2076d2a4-6b09-11e8-91db-42010a80010f
              executorInstanceId=i4iwiygr
              executorType=newdeploy
              functionName=hellopython-794508904
              functionUid=20890536-6b09-11e8-91db-42010a80010f
Annotations:  <none>
Subsets:
  Addresses:          10.52.5.150
  NotReadyAddresses:  <none>
  Ports:
    Name              Port  Protocol
    ----              ----  --------
    runtime-env-port  8888  TCP
    fetcher-port      8000  TCP
Events:  <none>
```

So then we look at IPTables on each node. 10:46:05 is when the pod update was fired. Within 15-20 seconds, all nodes recieve the new IP to be populated in the IP table rules of all 6 nodes:

```
Fri Jun 8 10:46:23 UTC 2018:
Chain KUBE-SEP-WFCAE6PG3KLQWPF3 (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.52.5.150          anywhere             /* f-func-e7675c/hellopython-794508904-i4iwiygr:runtime-env-port */
DNAT       tcp  --  anywhere             anywhere             /* f-func-e7675c/hellopython-794508904-i4iwiygr:runtime-env-port */ tcp to:10.52.5.150:8888
```
Also the IP address of old terminating pod was last seen at 10:46:15 in node iptables rules.

Even sending a curl request to service IP/address gives correct and expected result:

```
curl 10.55.251.148
Hello, fission!
```
So it does not look like an issue with iptables update propogation. Investgating more.

**Comment by vishal-biyani** [comment]
After ruling out the iptables / Kubernetes networking as a problem, another test was done to see if the router is caching something. Although the router says it is reaching to service, it is probably caching the IP address of target pod at some level (At go lang library level). 

To confirm this hypothesis here is the test conducted: after the function is updated in test_nd_pkg_update.sh - and the test for new value starts, we kill router. If there is some cache in router, then it will get cleared and we should get the new result (Hello Fission!). As confirmed by test in build https://travis-ci.org/fission/fission/builds/389743949 - this works, i.e. router is indeed caching the IP of pod somewhere and using that to connect.

After updating the function but before killing the router:

```
Events:  <none>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0   2298      0 --:--:-- --:--:-- --:--:--  2600

Hello, world!
```
Then we kill the router pod:

```
$ kubectl get pods -n f-9553bb
NAME                              READY     STATUS    RESTARTS   AGE
router-6f486fd6f4-vfbfq           1/1       Running   0          4m

$ kubectl delete pods router-6f486fd6f4-vfbfq -n f-9553bb
pod "router-6f486fd6f4-vfbfq" deleted

$ kubectl get pods -n f-9553bb
NAME                              READY     STATUS        RESTARTS   AGE
router-6f486fd6f4-bc5dm           1/1       Running       0          13s

```
This confirms the hypothesis and some cache from go lang used in router is culprit.

Code in functionHandler.go around line 160 needs further deep dive at go lang library level to determine how it is being cached and how that can be avoided.

```
		resp, err = transport.RoundTrip(req)
```

**Comment by vishal-biyani** [comment]
Conntrack logs did not reveal much information in addition to what `iptables` already showed us.  The current fix in #742 sets `DisableKeepAlives` to true thus removing all the caching - which is not good as it will cause performance degradation. Benchmarks with the setting enabled and disabled [can be found here](https://stackimpact.com/blog/practical-golang-benchmarks/#http-server).

An alternate solution is to use `CloseIdleConnections()` on the `transport` only in case of function updates. Overall flow for this change looks like below:

1) On a function update which changes the IP address of pod, executor needs to close all idle connections in router pods (Since there is no way to get 
2) Executor finds all pods behind the router service and calls an endpoint to flush connections on all router pods
3) All idle connections are closed (Need to check if we can do this only for that function/route level)
4) All further incoming requests for the function will use a fresh connection.

**Comment by vishal-biyani** [comment]
As discussed [here](https://github.com/fission/fission/pull/742#issuecomment-398825858) we will for now use `DisableKeepAlives` and optimize later with solution listed in previous comment.

**Comment by life1347** [comment]
@vishal-biyani , from the issue (https://github.com/golang/go/issues/13998) and code change (https://go-review.googlesource.com/c/go/+/22670/2/src/net/http/transport.go#146), looks like we only need to set up keep-alive timeout by `transport.IdleConnTimeout` to solve the problem.

**Comment by life1347** [comment]
Also, there is another japanese post mentioned the DNS result cache problem: https://shogo82148.github.io/blog/2017/01/14/re-golang-dns-cache/

**Comment by soamvasani** [comment]
#742 seems to be a good enough fix for this release.

**Comment by vishal-biyani** [comment]
I am closing this for now but we can revisit this in future if needed.
