### ISSUE TITLE
Using k8s' service to load balance the function's request may meet some performance issue.

### ISSUE THREAD

**Issue by hjianhao** [fission/fission#73]
We have test that, if we are using k8s service in a large scale cluster and massive service and pod scenario, it will face the serious latency issues. 

In a 1000 node, 4000 pod, 600 service condition, the 1000 req/sec request's average latency will be 8 times of directly forwarding to the pod's port.  Because the k8s' default mechanism will add many iptable's item in one node as the service number increase, that cause a dramatic performance decreasing( we using another network implementation to avoid this). 

In a large scale serverless scenario, there are many  functions and function runtime instance, so it's not a small problem in time critical  task.

**Comment by soamvasani** [comment]
That's interesting -- I'd like to learn more.  Is there a blog post or something I can read?  Have you brought this to Kubernetes team's attention?  What is the absolute latency overhead of services in your deployment?

I'm going to close this bug because this really isn't the right forum for Kubernetes scalability issues -- it's too early for us to decide that we should work around the problem in fission when we don't know enough about the problem.

Could you please file a Kubernetes issue or bring it up on the kubernetes-dev slack or mailing list?

**Comment by hjianhao** [comment]
We had tested in our real scene, but it's not a isolate case, there are already a few open issues of kubernetes. for example : https://github.com/kubernetes/kubernetes/issues/14099. It's really need to think about in large cluster scene. :)

**Comment by soamvasani** [comment]
Thanks. I'll keep an eye out for this problem when we get to testing deployments that size.
