### ISSUE TITLE
fluentd config as configmap

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#765]
Today we build the fluentd configuration file into the docker image.  We should use a configmap instead, so that users can easily override it (for example to send logs to a service like splunk).

**Comment by erwinvaneyk** [comment]
This might be worth exploring: https://github.com/vmware/kube-fluentd-operator

**Comment by vishal-biyani** [comment]
As an alternative to enabling a custom configmap - may be there should be a way to disable Fission FluentD and instead use existing FluentD/other forwarders. One side effect of that is the `fission fn logs` potentially not working unless you explicitly add influxDB forwarding. Also, some users want their own FluentD so that they can collate logs from other namespaces/applications and not just Fission function namespaces.

**Comment by life1347** [comment]
Solved by #792
