### ISSUE TITLE
Workflow Engine

### ISSUE THREAD

**Issue by xiekeyang** [fission/fission#830]
## Background

We support user to invoke many functions via one HTTP request, which is implemented in `fission-workflow` project.

The brief flowing is that user create a workflow environment, to resolve the workflow spec file. And then create a workflow function, to upload the workflow spec.

## Invocation Flowing:

1.User request to the workflow trigger;

2. Workflow-env specialize and resolve spec file. 

3. Internally workflow-env store the resolved tasks to event queue;

4. Workflow-env invoke the tasks from event storage;

5. Workflow compose the tasks according to internal runtime definition;

6. Workflow trigger returns the response;

## Problem:

Above invocation chain seems too long, and decrease the performance. 
I tested experiment to show that a `hello print` Python function is about 20ms, but the workflow function to wrap this function will cost about 300ms.

## Concept

Setup a workflow engine to instead workflow environment. This is deployed in fission-executor service, or play as an individual fission service.

The workflow engine plays role similar to current workflow env. 

* Defines internal runtime, like `compose`, `sleep`, `noop`...;

* Resolve the tasks, to determine the invocation contents and rule (like DAG data structure);

* Store the events, and communicate with Message queue such as NATS;

To do this, we may consider the below flowing:

### Specialization

* We have already created many functions, which need to be invoked by workflow;

* Add these functions to event store, and create a workflow task to invoke them;

* Create a Message Queue Trigger URL for the workflow task (inside router);

### Invocation

* User send request to the exist URL of Message Queue Trigger via $FISSION_ROUTER;

* Router identify this is mqt URL, and round the request to workflow engine directly;

* Workflow Engine resolve the request, to identify the invocation subject, which had been stored in event store. And identify the internal runtimes if exist;

* Workflow Engine invokes the event store, and all related functions are subscribed immediately, with sync or async. They are complied with DAG data structure;

* Return the response;

The above idea might bring the benefits to simply the invocation chain and crease the invocation performance. 

* The router URL is addressed only once anyway;

* The round to workflow engine or package in executor is executed only once;

* The main works are done inside workflow engine internally;

* Workflow need only communicate with backend service like NATS, to invoke the functions;

### Workflow Spec

This segment brings a bit controversial topic. 

Currently workflow env accept yaml file as workflow spec and store it in storage service, like common functions. When invocation, it has to be specialized and resolved to WorkFlowSpec structure.

This has to do file w/r and yaml parser. But actually workflow spec is pure structure, unlike common function files which are achieve.

So we might consider to define new type CRD like `Task` or `Workflow`, to instead spec file. This allow us to fetch or modify them via K8S go-client functions directly, which I assume is faster and safety.

The above is just my rough idea. And I made simple conversation with @erwinvaneyk 

Any proposal or supplement, please feel free to put up. Thanks.

Ping @erwinvaneyk @fission-maintainers

**Comment by soamvasani** [comment]
Hey @xiekeyang, I don't fully understand this proposal so I'll try going through it a bit.  Maybe it's a better discussion for Slack


> Above invocation chain seems too long, and decrease the performance.
> I tested experiment to show that a hello print Python function is about 20ms, but the workflow function to wrap this function will cost about 300ms.

This is a good point.  We should certainly work to improve that 300msec time.  A good first step would be to understand the overhead better.  Then we can figure out what optimizations can be done.  (For example if most of the overhead is from the event persistence, we could use the memory-backed NATS or even eliminate the roundtrip to the queue by keeping the log in the workflow engine's memory.)  But first we need to analyse performance to understand where the bottlenecks really are.

About your proposal -- the main difference that I can tell is that the workflow engine should use the MQTrigger instead of pushing messages to NATS directly.  I'm not sure I understand why this is better for performance; the router _does_ get involved, even when you use the MQTrigger.  If you still see some advantages to this, we can discuss it as a possible change to the workflow engine itself.

> So we might consider to define new type CRD like Task or Workflow, to instead spec file. This allow us to fetch or modify them via K8S go-client functions directly, which I assume is faster and safety.

This part of your idea is very interesting!  We do store the workflow in a Package CRD today, but as you said, it isn't currently modeled as an object in the K8s API.  That's definitely something we should think about doing!  It would have some nice advantages, like being visible to all K8s clients, and we could separate the workflow language from its implementation.  Let's discuss this as an issue on the fission-workflows repo.

**Comment by soamvasani** [comment]
@xiekeyang I'm going to close this issue in favor of tracking more specific issues.  Please keep discussions open on the Slack, especially with @erwinvaneyk , who's working on the fission workflow project.
