### ISSUE TITLE
Flask update needed

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#896]
Github's automated vulnerability scanning stuff notified us that one of our dependencies has a known vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2018-1000656

It suggests updating our python env's requirements.txt with:

```
flask ~> 0.12.3 
```

It seems to be moderate in severity so I think we can wait for 0.12.

**Comment by thenamly** [comment]
Before closing this issue with @life1347 fix, I still believe more flask update needed.

In the 0.6 version of the fission workflows, @erwinvaneyk sends chunked transfer encoding. 
(I guess it is for keeping memory usage low by piping data through nats? that's another topic)

However, chunked encoding have problems that solved in werkzeug 0.13 (https://github.com/pallets/werkzeug/pull/1198). If we upgrade flask 1.0+, werkzeug will be updated too.

Otherwise, practically empty body is coming when you use a python/flask based function in your workflows.

Are there any reason we are using 0.x.x versions?

**Comment by thenamly** [comment]
I updated flask to ~1.x.x but I figured out that also WSGI servers (gevent and bj.. here) need to support chunked encoding. Gevent do but they haven't added one flag for werkzeug (hence flask) to work. As a workaround, we pass the flag by adding following to the server.py

```
        @self.before_request
        def fix_transfer_encoding():
            """
            Without this, flask returns empty body on requests with chunked transfer encoding.
            The WSGI server (gevent, gunicorn...) should do this step when request is chunked
            However, even most WSGI servers support chunked transfer,
            their implementation is still missing wsgi.input_terminated set to True
            """
            if request.headers.get('Transfer-Encoding', '').lower() == 'chunked':
                request.environ['wsgi.input_terminated'] = True
```

Now, fission workflows chunked transfer encoded requests work but we will see if there is any other problem coming up with new 0.6 version of the fission workflows. We are excited to see overall improvement from @erwinvaneyk great work on last release!

**Comment by life1347** [comment]
Use a new issue to track the problem mentioned above. Close this one.
