### ISSUE TITLE
Fission environment for Java

### ISSUE THREAD

**Issue by mnowrot** [fission/fission#91]
Hi,

is there a roadmap for implementing Java env in fission?

Cheers,
Marcin

**Comment by Marak** [comment]
@mnowrot - Java is probably going to be hard for these kinds of services primarily due to the warm-up time of a fresh JVM.

**Comment by soamvasani** [comment]
We'd love to have Java support.  It would depend on #24, adding a builder.  The environment would dynamically load class files --  there would not be a JVM startup in the cold-start request path.

Java support isn't being directly worked on right now, though.  The solution for #24 is in currently in the design stage.

**Comment by tobias** [comment]
I'd be happy to work on a v2 Java environment. I'll work on a design unless someone else has already started on this.

**Comment by Marak** [comment]
I did some work on FAAS Java support and it's actually pretty performant. 

@soamvasani is correct in that this requires a build step.

Once you build the `.class` file it's good to go. One consideration we are facing now is whether to enforce a single class name for the exported JavaClass, and or use a manifest file.

There has also been a bit of discussion about implementing [Java Servlet API](https://en.wikipedia.org/wiki/Java_servlet). discussion at: https://github.com/Stackvana/microcule/pull/26

**Comment by Marak** [comment]
@tobias -

What would the proposed Java API look like for services?

Would it be working with STDIN / STDOUT, or would it use some sort of Java Servlet API? 

Lambda appears to use a buffered context for Java services? http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-handler-types.html

Will it be possible to get request / response streaming interfaces inside of Java services?

**Comment by tobias** [comment]
I've played with this a bit, and have a partial implementation. Just
as the javascript runtime embraces node.js (which isn't controversial,
given it's the most commonly used server-side js platform), I've built
my implementation around [Vert.x](http://vertx.io), a popular async
platform for Java (this may be more controversial, since there are a
plethora of choices on the JVM).

I didn't choose the Servlet API, because it brings a bit of baggage,
and the async support there is awkward. But work on a Vert.x
environment doesn't preclude a Servlet-based environment in the
future.

# The API

On to the API. Users would need to implement an interface to define a
function:

```java
package io.fission.api;

public interface Function<I> {
    void call(I input, Context context);
}
```

The input type (`I`) can be any type that the body of the request can
be coerced to (`String`, `vertx.JsonObject`, `vertx.JsonArray` (Vert.x
has built-in JSON support) are currently implemented, `vertx.FileSet`
is planned for supporting file uploads). This is a convenience so the
user doesn't have to handle reading and converting the body.

The `Context` interface currently looks like:

```java
package io.fission.api;

import java.nio.charset.Charset;

import io.fission.api.impl.ContextImpl;
import io.vertx.core.Vertx;
import io.vertx.core.http.HttpServerRequest;
import io.vertx.core.http.HttpServerResponse;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.web.RoutingContext;

public interface Context {
    static Context from(final RoutingContext ctx) {
        return new ContextImpl(ctx);
    }

    Vertx vertx();

    HttpServerRequest request();

    HttpServerResponse response();

    void fail(Throwable t);

    void fail(Throwable t, int status);

    Context setStatusCode(int code);

    Context setContentType(String type);

    void end();

    void end(String out);

    void end(String out, Charset encoding);

    void end(JsonArray out);

    void end(JsonObject out);
}
```

This interface would expand as desired to expose Fission-specific info
to the function.

Every function would be responsible for calling either one of the
`fail()` or `end()` methods to complete the request.

With these two interfaces, we can support simple functions like:

```java
package io.fission.java.sample;

import io.fission.api.Context;
import io.fission.api.Function;
import io.vertx.core.json.JsonObject;

public class JsonBody implements Function<JsonObject> {
    @Override
    public void call(JsonObject input, Context context) {
        System.out.println(input);
        input.put("modified", true);
        context.end(input);
    }
}
```

and the `Context` interface provides enough access to the underlying
Vert.x system and the request/response pair to do more complicated
things, like streaming in the request and/or streaming out the
response. You could also make use of the Vert.x event loop to do other
async work that eventually calls `fail()`/`end()`, either on the
`Context` or the `response()`. Using `Void` as the input type (`I`)
signals that the body shouldn't be read in by the server, allowing the
function to set up its own parsing/streaming/whatever.

# Packaging/Loading

The server expects the code to provided as a standard jar file that
can be produced by any of the standard java build tools. This jar must
contain the .class file(s) for the function, along with the .class
files for any dependencies that the function needs outside of what is
already provided by the server (Vert.x and its dependency tree,
basically).

When the `/specialize` route is hit, the jar is loaded from a known
location and added as a source to a new classloader. The name of the
class that implements the function is read from the request to
`/specialize`, and that class is then loaded using that classloader,
and is validated to make sure it conforms to the `Function` interface
and has a valid input type (`I`).

**Aside**: This expectation that the name of the function class be
  provided via the specialization request is something that isn't
  covered in the current v2 function creation API, but I'm trying to
  avoid encoding the name of the function to use within the jar file
  (in a manifest of some type) to allow reuse of the same jar file for
  different functions without having to rebuild, and I wanted to avoid
  an extra build step to wrap the .jar up in a another archive that
  would include the manifest. This is probably a discussion that
  should happen elsewhere - I just wanted to note it while I was
  thinking about it.

I haven't built a docker image from this yet to use in Fission, since
it relies on environments v2. But, running locally, the time to load a
simple function is ~5ms, with the first request taking ~230ms and
future requests taking ~1ms. I suspect the 230ms is due to the JVM
lazy-loading classes as they are needed, but we may be able to improve
that.

The code is currently in a separate repo
(https://github.com/tobias/fission-java-env/), but I'm happy to bring
it into the Fission repo if this is the approved implementation of the
java environment once v2 lands.

This doesn't currently involve a builder image for the environment - I
think it makes sense to let standard build tools build the archive
here, but a builder image might be useful for validation, ensuring the
function objects are valid before the first request.

**Comment by soamvasani** [comment]
@tobias Nice!! Overall this sounds pretty great! 

I don't know enough to have an opinion about Vert.x, but as you said, this doesn't preclude someone making another non-vertx JVM environment.  Using a framework to reduce boilerplate is definitely a good idea in general.

Some novice questions about vertx-- what happens if you define a function for JSON only, but there's a request that's not JSON?  Does Vert.x just error out in that case?  It would be good to have an example of something where the content-type of the request body is not known in advance.

> This expectation that the name of the function class be
provided via the specialization request is something that isn't
covered in the current v2 function creation API

Hmm, ok, sounds like this is worth adding (let's use #103 and the environments v2 doc for discussion).

The 230ms cold start is not too bad!  How big is a "hello world" jar?

**Comment by tobias** [comment]
> Some novice questions about vertx-- what happens if you define a
> function for JSON only, but there's a request that's not JSON? Does
> Vert.x just error out in that case? It would be good to have an
> example of something where the content-type of the request body is
> not known in advance.

The `Function` abstraction here is something I've built on top of
Vert.x - as is the coercion of the request body. My thinking there is
you are defining a function that just happens to be invoked over HTTP,
so you expect the input to be of a certain type. If the caller
provides input of a different type, that is an error on the caller's
part. In the current implementation, giving invalid input (input that
can't be coerced to the type in the `call` method's signature) results
in a 400 error to the caller.

However, there is an escape hatch here if you want to process the body
yourself, either because you don't know what the type will be, or want
to handle the body in some other way (as a stream, for example). If
you specify the input type as `Void`, that doesn't mean the request
must have a void (nil/empty) body, but means don't coerce the body. In
that case, the function is responsible for handling it on it's own.

A rough example of that would be:

```java
package io.fission.java.sample;

import io.fission.api.Context;
import io.fission.api.Function;
import io.vertx.core.json.DecodeException;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;

public class UnknownBody implements Function<Void> {
    @Override
    public void call(Void input, Context context) {
        // this should probably be a convenience method on the Context
        final String contentType = context.request().getHeader("Content-Type");

        // bodyHandler will get called when the body is fully read.
        // There are other methods for reading the body in chunks as it comes in
        context.request().bodyHandler(body -> {

            switch (contentType) {
                case "text/plain":
                    final String str = body.toString();
                    // do something with the data
                    break;
                case "application/json":
                    try {
                        final JsonObject json = new JsonObject(body.toString());
                        // do something with the data
                    } catch (DecodeException ex) {
                        final JsonArray json = new JsonArray(body.toString());
                        // do something with the data
                    }
                    break;
                default:
                    context.setStatusCode(400).end("Unexpected content-type " + contentType);
                    return;
            }

            context.end("ok");
        });
    }
}
```


> The 230ms cold start is not too bad! How big is a "hello world" jar?

The jar is pretty small at this point (4.9K), since it just has the
three [sample implementations](https://github.com/tobias/fission-java-env/tree/master/sample/src/main/java/io/fission/java/sample) in it, with no dependencies.
That 230ms is the lazy loading of all of the classes needed to parse JSON.
If I warm that up by exercising the JSON parsing when starting up the server,
the first request time drops to 2ms. We certainly can't preload all of the
classes that a user's function may need, especially if those classes only
exist in the jar file, so the first request time will still be highly
dependent on the amount of classes they use.

**Comment by soamvasani** [comment]
I see, thanks for the example!  Makes total sense.  I like the Function abstraction, I didn't at first realize it's separate from Vertx.

BTW, does the user have a way to add some code to an "init" path, such that the code is executed only on cold start?  This is useful for making DB connections efficient, for example.

**Comment by tobias** [comment]
There's no explicit mechanism for that - I would expect users would lazy-initialize needed resources, with synchronization:

```java
private DBConnection dbcon;

synchronized DBConnection dbConnection() {
  if (this.dbcon == null) {
    this.dbcon = makeADBConnection();
  }
  return this.dbcon;
}
```

**Comment by ledor473** [comment]
:+1: for Java (8 ?) support !

I kinda like the way AWS Lambda deals with it and here's a breakdown of what exactly:

#### No Interface / Naming
There's no Interface to implement and no strict naming.
You just specify the package and class name. If you want a different method name, you can specify it optionally.

I'm not against having a minimal Interface (ref 2) or a few predefined POJO, but having to include Vertx (or *any* framework really) just to access a deserialized object is a bit too much.

Why? Classpath conflict and also I think that the only mandatory dependency should be what's included in the JDK.

#### Bring your own serialization
AWS Lambda can either deserialize your request into a POJO of your choice and serialize your response into another one.
If you want more control over the settings, you can receive it as a String or even the raw byte stream (both Input and Output)

--- 

Here's some thoughts on what was already discussed in this thread:

#### Init code
I cant find the reference in the AWS documentation (see a blog post in ref 3), but I think that AWS Lambda initialize the class only on cold start.
Any successive invocation on the same worker will just call the handler method.

As a user you dont have to use `synchronized` on any method if you do such work in the constructor.

I'm not saying its ideal, just wanted to point out another option :)

 #### Logging
AWS Lambda provides the following options (ref 4):
- System.out() / System.err()
- A Logger passed in the Context object during the invokation of the handler
- A separate JAR that includes a custom Appender for Log4j 1.2
  - That makes it easier to port code that is already written to AWS Lambda

---

#### References: 
1. http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-req-resp.html
2. aws-lambda-java-core (http://docs.aws.amazon.com/lambda/latest/dg/java-handler-using-predefined-interfaces.html)
3. http://blog.rowanudell.com/database-connections-in-lambda/
4. http://docs.aws.amazon.com/lambda/latest/dg/java-logging.html

**Comment by lev-kuznetsov** [comment]
Is there any reason why JAX-RS spec can't be implemented? That way there's a standard API and a lot of already existing code would work out of the box.

Basic interface looks like this:

```java
@POST
int factorial (@FormParam ("x") int x) { return x < 1 ? 1 : x * factorial (x - 1); }

@POST
@Path ("{id}")
Foo /* <- return as json */ doStuff (@PathParam ("id") String id, Bar bar /* <- read as json */) {
  // stuff
}
```

There's plenty of implementations, here's a blog post on async here: https://dzone.com/articles/jax-rs-20-asynchronous-server-and-client 

Serialization is handled by each of the implementations, Jackson is most configurable and would be appreciated. Bootstrap is usually automatic via classpath scan done normally by an application container, but I think it's totally reasonable to provide a separate configuration file for the bootstrap. So deployment artifact would be a fat jar with all dependencies and a specially named file in jar:/META-INF/fission.yaml for example that describes endpoints to deploy

**Comment by vishal-biyani** [comment]
@soamvasani I am going to take this up from here

**Comment by vishal-biyani** [comment]
Related: #656

**Comment by vishal-biyani** [comment]
Closing this issue. Will create separate issues for new features & additions in Java environment.
