### ISSUE TITLE
Canary deployment max iterations

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#921]
Do we need a maximum iteration number for canaries at all?  It is currently set very low, at 10.  This would seem to prevent increments lower than 10%.  Even if we do need such a maximum, it should be configurable in the canary config spec.

**Comment by smruthi2187** [comment]
Maximum iteration is defined to prevent the go routine that processes the canary config from running infinitely. Agree that it's set to very low value now and we can set it to a high value.
Also, this need not be a per config parameter because it's immaterial to the user/creator of canary config. This parameter is to solely safeguard fission from bloating up due to multiple go routines running infinitely.

**Comment by soamvasani** [comment]
Agree that this is an implementation thing that the user shouldn't care about.  However the user is affected when we run out of max iterations.  

Goroutines are relatively cheap.  If it's sleeping most of the time it probably isn't too bad in terms of resource usage.  That said, if too many long running goroutines is a concern, maybe you could consider some design where there isn't one goroutine per canary?
